### ISSUE TITLE
"API not found with these values" on some nodes of Kong Cluster

### ISSUE THREAD

**Issue by chicoandrade** [Mashape/kong#1444] opened 2016-07-26 16:01 UTC
### Summary

We have a 14 nodes Kong Cluster running in Production with Kong version 0.8.1.
Most of the time the cluster is stable, but occasionally some nodes begin to return 404 "API not found with these values" for all the apis registered on the cluster:

> {
> "request_path": "/solr/soub/core/select",
> "message": "API not found with these values",
> "request_host": [
> "10.x.x.x"
> ]
> }

The problem usually resolves when we restart the problematic node. But sometimes a few minutes later the node goes back to the problematic state.
When we access the admin console (8001/apis), all the apis are listed there.
### Steps To Reproduce
1. Create a Kong Cluster
2. Register an api
3. Create a healthcheck to monitor the api
4. Wait for the problem to happen
### Additional Details & Logs
- Kong version 0.8.1
- Kong configuration: 17 apis with customized plugins
- Kong error logs: NA
- Operating System: Ubuntu
- Kong environemnt: Docker container

**Comment by chicoandrade** [comment] 2016-07-26 19:45
I'm using a script that checks if all nodes are returning 200 when requesting the api url:
```
$ for i in {1..14}; do echo host-$i; curl -is "http://host-${i}/solr/soub/core/select?q=itemId:123&wt=json&fl=itemId" | grep HTTP ; done
host-1
HTTP/1.1 200 OK
host-2
HTTP/1.1 404 Not Found
host-3
HTTP/1.1 200 OK
host-4
HTTP/1.1 200 OK
host-5
HTTP/1.1 200 OK
host-6
HTTP/1.1 404 Not Found
host-7
HTTP/1.1 200 OK
host-8
HTTP/1.1 404 Not Found
host-9
HTTP/1.1 200 OK
host-10
HTTP/1.1 200 OK
host-11
HTTP/1.1 404 Not Found
host-12
HTTP/1.1 200 OK
host-13
HTTP/1.1 200 OK
host-14
HTTP/1.1 200 OK
```

**Comment by thefosk** [comment] 2016-07-27 01:20
@chicoandrade did you notice if the problem happens randomly or after a CRUD operation being executed on an API (like updating an API using Kong's port 8001?)

**Comment by chicoandrade** [comment] 2016-07-27 13:17
Hi @thefosk, the cluster was stable for at least 8 weeks, then yesterday the problem started to happen a few minutes after we register a new api

**Comment by thefosk** [comment] 2016-07-28 02:25
@chicoandrade are all the Kong nodes properly active when you request `:8001/cluster` ?

**Comment by allisthere2love** [comment] 2016-07-28 14:05
Hi @thefosk,

When the problem occurs, all the nodes appears as active in /cluster.
Also, the API that gives 404 when accessed, appears in /apis

**Comment by allisthere2love** [comment] 2016-08-02 18:48
@thefosk ,

Since we've opened this issue, we didn't have the problem. But we've removed the "extra api" and didn't included it again, fearing for this error in production.

If you have any tips on how to debug this (seems like someone in the API crud, but I'm not certain) you can send us the modified code in gist or something else and we'll build a custom "debug" kong here to test. Maybe some extra output help us all to find what's happening.

**Comment by thefosk** [comment] 2016-08-25 06:16
Interesting. I will try to replicate this issue, please let me know if you experience again the same problem.

**Comment by nullfox** [comment] 2016-08-29 20:11
Chiming in to say we're running 0.8.3 docker-kong and seeing this issue as well. After updating the request host for an API were seeing inconsistent 404s in the same was as described in the original issue.

The only thing that seems to completely fix this is to deploy a new set of instances and bring down all of the old ones.

Happy to provide any info that may be relevant/helpful.

**Comment by thefosk** [comment] 2016-08-29 20:13
I wonder if this is caused by #1074 - since then I have republished the 0.8.3 Docker image so you need to explicitly re-pull it, or upgrade to 0.9.

**Comment by nullfox** [comment] 2016-08-29 21:28
I should say that this has been found to be a non-issue on our end. This looks to have been caused by funky networking issues causing certain nodes to fail to join the serf cluster.

**Comment by Tieske** [comment] 2016-12-03 13:54
I'm closing this for now. Feel free to reopen if the issue reoccurs.

**Closed by Tieske** 2016-12-03 13:54 UTC
Labels: area/cluster
