### ISSUE TITLE
How to verify that it is Kong calling my backend?

### ISSUE THREAD

**Issue by angusfz** [Mashape/kong#1528] opened 2016-08-22 09:52 UTC
Hi All,
 AWS API gateway provide client-side SSL certificate to prevent API abuse or threats.
Does Kong support such function ?

ManyThank
Angus

**Comment by thefosk** [comment] 2016-08-23 06:07
You will need to customize the nginx configuration to do so. Duplicate of #1357

**Closed by thefosk** 2016-08-23 06:07 UTC
