### ISSUE TITLE
Invalid JSON input returns 500 instead of 400

### ISSUE THREAD

**Issue by brian17han** [Mashape/kong#1826] opened 2016-11-16 15:10 UTC
### Summary

We currently ran into an issue that we get 500 back if user sends invalid JSON (e.g. missing the closing curly brace) to our API. Our code has an exception mapper for this and it will return 400, but seems like it never reaches our proxy and 500 is returned by Kong.

### Steps To Reproduce

1. Use invalid JSON (e.g. missing the closing curly brace) as input body for any of the PUT or POST calls
2. Make the API call
3. Kong returns 500

### Additional Details & Logs

- Kong version (0.9.0)

**Comment by Tieske** [comment] 2016-11-16 15:28
Can you still reproduce it with 0.9.5?

**Comment by thefosk** [comment] 2016-11-17 00:38
What plugins are you using on the API? @brian17han

**Comment by brian17han** [comment] 2016-11-17 14:42
@Tieske We will try to upgrade later this week and I will post the outcome here. Thanks

**Comment by brian17han** [comment] 2016-11-17 14:47
@thefosk We use oauth2 and galileo.

**Comment by thefosk** [comment] 2016-11-17 19:49
I think the problem is that with an `Accept: application/json` header, if the body has a missing or invalid JSON, we don't catch the exception and thus a 500 is being returned.

I will try to submit a patch wherever we are parsing the body in our plugins.

**Comment by brian17han** [comment] 2016-11-17 19:52
@thefosk Thanks for you help, I will wait for the update.

**Comment by thefosk** [comment] 2017-01-05 20:33
Fixed in 0.10

**Closed by thefosk** 2017-01-05 20:33 UTC
Labels: oauth2, task/bug
