### ISSUE TITLE
 API execution fails in a forward proxy environment.

### ISSUE THREAD

**Issue by 2TomS** [Mashape/kong#1271] opened 2016-05-31 09:33 UTC
Added Mockbin API and the Kong HP(https://getkong.org/docs/0.8.x/getting-started/quickstart/) to reference the company's environment(Authentication is required forward proxy environment).
However, the result was the following.

<pre>
# curl -i -X POST \
--url http://10.169.222.137:8001/apis/ \
--data 'name=mockbin' \
--data 'upstream_url=http://mockbin.com/' \
--data 'request_host=mockbin.com'

HTTP/1.1 201 Created
Date: Tue, 31 May 2016 08:18:17 GMT
Content-Type: application/json; charset=utf-8
Access-Control-Allow-Origin: *
Server: kong/0.8.1
X-Cache: MISS from proxy.example
X-Cache-Lookup: MISS from proxy.example:8080
Transfer-Encoding: chunked
Via: 1.1 proxy.example
Connection: keep-alive

{"upstream_url":"http:\/\/mockbin.com\/","created_at":1463724674000,"id":"9b0c52e9-956b-4d00-9488-f6af9b5c4af0","name":"mockbin","preserve_host":false,"strip_request_path":false,"request_host":"mockbin.com"}
</pre>

<pre>
# curl -i -X GET \
--url http://10.169.222.137:8000/ \
--header 'Host: mockbin.com'

HTTP/1.1 404 Not Found
Date: Tue, 31 May 2016 08:20:20 GMT
Content-Type: application/json; charset=utf-8
Server: kong/0.8.1
X-Cache: MISS from proxy.example
X-Cache-Lookup: MISS from proxy.example:8080
Transfer-Encoding: chunked
Via: 1.1 proxy.example
Connection: keep-alive

{"request_path":"\/","message":"API not found with these values","request_host":["10.169.222.137"]}
</pre>

There was no problem at home is not a proxy environment.
Do forward proxy environment has been affected?
Or, does it the following message to be output to the Kong start has been affected?

<pre>
[WARN] Cannot auto-join the cluster because no nodes were found
[WARN] The internet connection might not be available, cannot resolve kong-hf.mashape.com
</pre>

Sorry... I am not good at English.
If there is a mistake, please point out.

**Comment by 2TomS** [comment] 2016-06-02 01:46
Sorry... I am not good at English.
If there is a mistake, please point out.

**Comment by Tieske** [comment] 2016-06-02 10:50
I cannot reproduce this, but the again, I don't have a proxy environment

using httppie (and explicitly using ip address, not localhost);
````
Mashapes-MacBook-Pro-2:kong thijs$ http post 192.168.1.21:8001/apis name=mockbin.com "upstream_url=http://mockbin.com" request_host=mockbin.com
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Jun 2016 10:36:25 GMT
Server: kong/0.8.3
Transfer-Encoding: chunked

{
    "created_at": 1464863786000,
    "id": "b4ca44eb-83fc-4680-8901-7d116bcdcc10",
    "name": "mockbin.com",
    "preserve_host": false,
    "request_host": "mockbin.com",
    "strip_request_path": false,
    "upstream_url": "http://mockbin.com"
}

Mashapes-MacBook-Pro-2:kong thijs$  http get 192.168.1.21:8000/ "host: mockbin.com"
HTTP/1.1 200 OK
CF-RAY: 2aca46dfe4cf2c30-AMS
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Thu, 02 Jun 2016 10:38:36 GMT

<snip>
````

The message you're getting;

> `{"request_path":"\/","message":"API not found with these values","request_host":["10.169.222.137"]}`

indicates that Kong tries to match based on the hostname "10.169.222.137", which seems to indicate that the header you pass to `curl` with `--header 'Host: mockbin.com'` is not received by Kong.

**Comment by 2TomS** [comment] 2016-06-06 09:18
Thank you for the reply.
And, I'm sorry my reply is slow.
Because it can be used at home, I will try to work in there.
But, it can not be used in the proxy environment is a concern.
I think want to survey continue.
If you ever want to try me, please say.

**Comment by Tieske** [comment] 2016-07-13 17:49
sorry for the late reply. It's a bit busy here right now.
have you been able to resolve this? 

going through it again; as it tries to match on the ip address, it seems that Kong did not receive the `host` header. So it appears as if the request was modified, probably due to your proxy.

if you cannot reconfigure your proxy to leave the host header in. Then the only alternative I see is not using the `request_host` field, but using a `request_path` when configuring your api.

**Comment by thibaultcha** [comment] 2016-09-01 22:52
Closing this due to lack of updates.

**Closed by thibaultcha** 2016-09-01 22:52 UTC
Labels: question
