### ISSUE TITLE
Setting a locale breaks the first run

### ISSUE THREAD

**Issue by CapacitorSet** [Mashape/kong#2105] opened 2017-02-18 20:28 UTC
### Summary

If the `it_IT` locale is set, `kong start` fails.

### Steps To Reproduce

1. Configure your system with the "Italian (Italy)" locale
2. ssh into a server
3. Install Kong, copy the default configuration
4. Run `kong start`

The command will fail with the errors below. This is probably not a minimal example; it could suffice to run Kong on a system with the Italian locale, or just with the appropriate environment variables.

Note that configuring sshd to not accept the `LANG` and `LC_*` environment variables fixes this.

### Additional Details & Logs

- Kong version (`$ kong version`): 0.9.9
- Kong debug-level startup logs (`$ kong start --vv`):

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_IDENTIFICATION = "it_IT.UTF-8",
	LC_TIME = "it_IT.UTF-8",
	LC_NUMERIC = "it_IT.UTF-8",
	LC_PAPER = "it_IT.UTF-8",
	LC_MEASUREMENT = "it_IT.UTF-8",
	LC_ADDRESS = "it_IT.UTF-8",
	LC_MONETARY = "it_IT.UTF-8",
	LC_NAME = "it_IT.UTF-8",
	LC_TELEPHONE = "it_IT.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
2017/02/18 21:18:19 [verbose] Kong: 0.9.9
2017/02/18 21:18:19 [verbose] reading config file at /etc/kong.conf
2017/02/18 21:18:19 [verbose] prefix in use: /usr/local/kong
2017/02/18 21:18:19 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/02/18 21:18:19 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/02/18 21:18:19 [verbose] could not start Kong, stopping services
2017/02/18 21:18:19 [verbose] leaving serf cluster
2017/02/18 21:18:19 [verbose] stopping dnsmasq at /usr/local/kong/pids/dnsmasq.pid
2017/02/18 21:18:19 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/utils/log.lua:49: bad argument #4 to 'format' (no value)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:89>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:89: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:13: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
```

- Kong error logs (`<KONG_PREFIX>/logs/error.log`): None
- Kong configuration (registered APIs/Plugins & configuration file): Default
- Operating System: Ubuntu 16.04

**Comment by thibaultcha** [comment] 2017-02-28 06:56
Hi,

Please see [this comment](https://github.com/Mashape/kong/issues/1832#issuecomment-275365816) if it works for you. In the meanwhile, I'll close this and consider it a duplicate of #1832.

**Closed by thibaultcha** 2017-02-28 06:56 UTC
