### ISSUE TITLE
Can't delete API by name

### ISSUE THREAD

**Issue by Lawouach** [Mashape/kong#1116] opened 2016-03-31 14:17 UTC
Hi folks,

The current API docs states we can delete an API by id or name. However, whenever I try to delete it by name, it tells me the API isn't found.

```
$ curl kong.service.consul:8001/apis/
{"data":[{"upstream_url":"http:\/\/test.service.consul:10000","id":"1feee03f-c053-4891-acb2-87952494903a","name":"test","created_at":1459433134000,"request_host":"test.service.consul"}],"total":1}

$ curl -X DELETE kong.service.consul:8001/apis/test
{"message":"Not found"}

$ curl -X DELETE kong.service.consul:8001/apis/1feee03f-c053-4891-acb2-87952494903a

$ curl kong.service.consul:8001/apis/
{"data":[], "total": 0}
```

Is the doc incorrect or am I missing something obvious?

Thanks guys,

**Comment by jimmypk** [comment] 2016-04-06 08:36
To manage Kong easily, use kong-dashboard:
https://github.com/PGBI/kong-dashboard
docker run -d --name kong-dashboard --restart=always -p 8080:8080 pgbi/kong-dashboard

**Comment by keithsherratt** [comment] 2016-11-02 16:26
I had exactly this problem and found out that the problem was that I had multiple API's with the same name.

When you try and delete an API that exists multiple times with the same name (e.g. using curl -X DELETE kong.service.consul:8001/apis/test), then you get the {"message":"Not found"} response and the only way around this (as shown in your example) is to delete via the ID.

NB Even when you have multiple names, the result from an attempt to retrieve the API will only return the first and so the problem is not evident unless you go into something like JUNGLE and list the API's.

When you only have a single API with a given name, then the delete will work

**Comment by Tieske** [comment] 2017-02-13 15:12
tested on 0.9.9, and works as expected. Can no longer create 2 apis with the same name, and also deleting by name works.

closing this.

**Closed by Tieske** 2017-02-13 15:12 UTC
Labels: area/admin api, task/bug

**Comment by divyanshuverma1** [comment] 2017-10-16 11:06
@Lawouach, i tried deleting my api's, its working for me using the below command.

# curl -i -X DELETE http://localhost:8001/apis/example-api
