### ISSUE TITLE
Support to call multiple upstream APIs for single client API call

### ISSUE THREAD

**Issue by yugansh20** [Mashape/kong#1364] opened 2016-07-05 12:04 UTC
Is there an option where one client call can lead Kong to call multiple backend APIs , combine the data and send???

**Comment by kylegato** [comment] 2016-07-08 19:35
@yugansh20 I believe the correct way to do this, is to follow generally accepted microservice architectures.

You should have orchestration APIs that talk to your backend resource APIs.

In this way it would be Client -> Kong -> Orch API -> Multiple backend Resource APIs -> Orch API -> Kong -> Client

**Comment by thefosk** [comment] 2016-07-11 23:22
This could be done in a custom plugin, delegating to Kong the ability of cascading requests. @yugansh20 can you give me an example of calls you would like to make?

**Comment by sinzone** [comment] 2016-07-11 23:44
#155

**Comment by Tieske** [comment] 2016-07-13 17:56
closing this as a duplicate of #155

**Closed by Tieske** 2016-07-13 17:56 UTC

**Comment by prasanthai** [comment] 2020-03-15 06:17
how to config in kong ? / do you have sample to config ?
