### ISSUE TITLE
OpenID Connect Implementation 

### ISSUE THREAD

**Issue by lg1712** [Mashape/kong#1440] opened 2016-07-25 09:05 UTC
OpenID Connect Implementation 

The current plugins offered by Kong do not support Open ID Connect.
http://openid.net/connect/

OpenID Connect support would be a must have to the Kong expansion over the other API Gateway solutions.

**Comment by Tieske** [comment] 2016-07-28 15:59
Duplicate of #522

**Closed** 2016-07-28 16:00 UTC
