### ISSUE TITLE
Kong integration with external OpenID connect service

### ISSUE THREAD

**Issue by vipinchandra** [Mashape/kong#1449] opened 2016-07-28 06:22 UTC
### Summary
If we already have an existing Identity and access management Service that is also a OpenID connect provider, is there a way to configure API setup in Kong to use such external service. Ex: KeyCloak is already setup to maintain user/customer federation and it already setup as OAuth2/OpenIdConnect authorization sever.  
Essentially having a OAuth2 type plugin but configured to point to external OAuth2 service.

Trying to re-use existing user/customer identity store (as many existing apps depends on them) and avoid resistant setup.

Is there a plan in future roadmap to support such feature?

Thanks
Vipin

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Operating System

**Comment by Tieske** [comment] 2016-07-28 16:00
Duplicate of #522

**Closed by Tieske** 2016-07-28 16:00 UTC
