### ISSUE TITLE
Resolver - Does path parameter supports regex now?

### ISSUE THREAD

**Issue by jeevanrd** [Mashape/kong#561] opened 2015-09-23 02:36 UTC
I saw one of your comments in https://github.com/Mashape/kong/pull/282 saying, it's on your todo task lists. would be glad to know the updates on it

Currently when I create a endpoint with path having "/abcd/[0-9]/" it throws error saying "path must only contain alphanumeric and '. -, _, ~, /' characters".

I realized after digging into resolver code that you are already doing regex based path matching using ngx.re.match function. I hope if you remove the alphanumeric condition in (dao/schemas/apis.lua), it should work straight away right?

**Comment by thibaultCha** [comment] 2015-09-23 12:12
See #369. Support of multiple path and host will give support for regex a sense. We have not decided when to start working on it. The issue is to implement an easy to use prioritisation system between multiple paths, which is easy in text configuration in nginx, but no so much when dealing with a REST API.

**Comment by jeevanrd** [comment] 2015-09-23 12:33
@thibaultCha any rough idea on timelines because we are kind of dependent on this feature.

**Comment by thibaultCha** [comment] 2015-10-15 03:33
No, no rough idea of when this will be implemented for now, sorry. Closing it as this was a question and #369 is the proper issue.

**Closed by thibaultCha** 2015-10-15 03:33 UTC
Labels: duplicate, question
