### ISSUE TITLE
API AGGREGATOR

### ISSUE THREAD

**Issue by alhassane** [Mashape/kong#1732] opened 2016-10-10 16:25 UTC
### Summary

Develop a plugin with the same approach of API Aggregator (https://github.com/solso/api-aggregator) due to adding API AGGREGATOR lua scripts

**Comment by thefosk** [comment] 2016-10-10 20:40
Duplicate of #155

**Closed by thefosk** 2016-10-10 20:40 UTC

**Comment by thibaultcha** [comment] 2016-10-10 20:57
This is an interesting approach to the problem of configuring such a feature though: making it scriptable
