### ISSUE TITLE
Kong incorrectly permits creating multiple certificates with same sni

### ISSUE THREAD

**Issue by Uvedale** [Mashape/kong#2275] opened 2017-03-28 07:34 UTC
### Summary

If I post multiple certificates with the same "snis" value to /certificates, the response becomes:

`<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body></body></html>`

I cannot remove the duplicate SNI, presumably because they are key'd on the same value. I get a 200 response with the same HTML response as above but the duplicate still exists. The SNI cannot be used by any APIs as it results in an SSL error.

### Steps To Reproduce

1. 
```
curl -i -X POST http://127.0.0.1:8001/certificates/ \ 
-d cert="dummycert" \
-d key="dummykey" \
-d snis=example.com
```
2.
```
curl -i -X POST http://127.0.0.1:8001/certificates/ \ 
-d cert="dummycert" \
-d key="dummykey" \
-d snis=example.com
```
3. `curl -i -X DELETE http://127.0.0.1:8001/snis/example.com`

### Additional Details & Logs

- Kong version (`$ kong version`): 0.10.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`): Just shows 200s
- Kong configuration (registered APIs/Plugins & configuration file): Default from docker image
- Operating System: Debian Jessie (3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux)

**Comment by p0pr0ck5** [comment] 2017-03-29 00:13
I'm unable to reproduce this. Attempting to create certificates sequentially with the same element in the `snis` field fails as expected:

```
vagrant@precise64:/kong$ curl -i -X POST http://127.0.0.1:8001/certificates/ -d cert="dummycert" -d key="dummykey" -d snis="example.com"HTTP/1.1 201 Created
Date: Wed, 29 Mar 2017 00:05:41 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

{"cert":"dummycert","id":"5cc0e7d4-9a2e-4387-aa72-d11f334db071","snis":["example.com"],"created_at":1490745941000,"key":"dummykey"}
vagrant@precise64:/kong$ curl -i -X POST http://127.0.0.1:8001/certificates/ -d cert="dummycert" -d key="dummykey" -d snis="example.com"HTTP/1.1 409 Conflict
Date: Wed, 29 Mar 2017 00:05:43 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

{"name":"already exists with value 'example.com'"}
vagrant@precise64:/kong$ curl -i -X POST http://127.0.0.1:8001/certificates/ -d cert="dummycert2" -d key="dummykey2" -d snis="example.com"
HTTP/1.1 409 Conflict
Date: Wed, 29 Mar 2017 00:05:49 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

{"name":"already exists with value 'example.com'"}
```

Only one SNI exists:

```
vagrant@precise64:/kong$ curl -i http://127.0.0.1:8001/snis/
HTTP/1.1 200 OK
Date: Wed, 29 Mar 2017 00:07:37 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

{"data":[{"name":"example.com","created_at":1490745941000,"ssl_certificate_id":"5cc0e7d4-9a2e-4387-aa72-d11f334db071"}],"total":1}
```

And deleting it works as expected:

```
vagrant@precise64:/kong$ curl -i -X DELETE http://127.0.0.1:8001/snis/example.com
HTTP/1.1 204 No Content
Date: Wed, 29 Mar 2017 00:08:00 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

vagrant@precise64:/kong$ curl -i http://127.0.0.1:8001/snis/
HTTP/1.1 200 OK
Date: Wed, 29 Mar 2017 00:08:03 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: false
Server: kong/0.10.1

{"data":[],"total":0}
```

**Comment by thibaultcha** [comment] 2017-03-29 00:29
I am willing to bet you two are not using the same database (Postgres/Cassandra). @p0pr0ck5 Are you on Cassandra when trying this?

**Comment by p0pr0ck5** [comment] 2017-03-29 04:02
@thibaultcha nice call, assuming this is the result of the unique constraint not being applied for the `name` field of the sni schema?

**Comment by p0pr0ck5** [comment] 2017-04-17 17:35
Closing, as this was fixed in https://github.com/Mashape/kong/commit/57ad9ffe586d102510f5fa987ce20494b87bb506.

**Closed by p0pr0ck5** 2017-04-17 17:35 UTC
