### ISSUE TITLE
Add metadata to consumer for postgress

### ISSUE THREAD

**Issue by schellkenig** [Mashape/kong#1621] opened 2016-09-13 07:25 UTC
It would be great if we can add additional metadata to the consumer. Kong could generate then an upstream header which contains this metadata.

**Comment by sinzone** [comment] 2016-09-13 07:34
we have something similar https://getkong.org/plugins/correlation-id/

**Comment by Tieske** [comment] 2016-09-13 14:58
when using authentication plugins, Kong already sends along some of the IDs, so upstream is able to identify the consumer (custom_id iirc). Relating this to consumer specific meta data is an upstream responsibility imo. Kong only identifies. No?

**Comment by schellkenig** [comment] 2016-09-13 15:17
Just to give you an example I would add a json in this custom metadata with the customer that contains the internal groups that the user belongs to, e.g., canary tester, etc. When the user hits the api gateway the gateway should simply add a header to all downstream requests with X-Custom-Metadata : myJson.

Even better would be if we could store individual key value pairs with each customer and make them selectable in the request-transformer like:

`config.add.headers[1]=x-new-header:{customer:mykey}`

**Comment by Dibble** [comment] 2016-09-13 15:38
@schellkenig have you considered configuring the Request Transformer plugin per consumer?

Something like this:
`curl -X POST <kong>/<api>/plugins -d "name=request-transformer" -d "consumer_id=<consumer id>" -d "config.add.headers[1]=x-new-header:{customer:mykey}"`

It might get a bit messy if you have a large number of consumers, but I think it should work.

**Comment by schellkenig** [comment] 2016-09-13 16:12
I would do this but the request-transfer is not capable of using values from the customer (to the best of my knowledge) and these values are also not present but probably I misunderstood here something?

**Comment by thibaultcha** [comment] 2016-09-13 18:35
Closing this as a duplicate of #550.

**Closed by thibaultcha** 2016-09-13 18:35 UTC
