### ISSUE TITLE
Key-auth authentication failing

### ISSUE THREAD

**Issue by anamarialazar** [Mashape/kong#1336] opened 2016-06-24 10:50 UTC
Hi all, 

I am using kongfig to configure my kong and everything looks good in the database but I cannot make a request. My journey is below:

Config:
```
apis:
  - name: api_products
      attributes:
        request_path: /products
        upstream_url: http://products.app.internal
      plugins:
        - name: file-log
          attributes:
            config:
              path: "/usr/local/kong/logs/kong.log"
        - name: trace
        - name: key-auth
          attributes:
              config:
                hide_credentials: true
                key_names:
                  - apikey
consumers:
    - username: admin
      credentials:
        - name: key-auth
          attributes:
            key: ThisTokenIsNotSoSecretChangeIt
```

The config looks it was imported correctly:

Request: `curl localhost:8001/consumers`
Response: 
```
{
    "data":[
        {
            "username":"admin",
            "created_at":1466764389000,
            "id":"9a746cee-81af-426f-a54c-04d6ea522f23"
        }
    ],
    "total":1
}

```
Request: `
curl localhost:8001/consumers/admin/key-auth`
Response:
```
{
    "data":[
        {
            "created_at":1466764389000,
            "consumer_id":"9a746cee-81af-426f-a54c-04d6ea522f23",
            "key":"ThisTokenIsNotSoSecretChangeIt",
            "id":"42bc0e6d-d5eb-40dc-990a-be8828ddcb25"
        }
    ],
    "total":1
}
```
However when I try to actually use the key:

Request: `curl -H "apikey: ThisTokenIsNotSoSecretChangeIt" localhost:8000/products`

Response:

```
{
    "message":"No API Key found in headers, body or querystring"
}
```
If I use an invalid key I get:
Request: `curl -H "apikey: AnotherRandomKey" localhost:8000/products`

Response:

```
{
    "message":"Invalid authentication credentials"
}
```
However if I delete the API and plugin and re-add them via curl requests then everything works without any problems. I think it's something related to cache but no idea how to debug this. Any advice?

**Comment by Tieske** [comment] 2016-06-24 15:32
I cannot reproduce this

Using a clean database (`kong migrations reset` and httpie);
```
http POST localhost:8001/apis name=httpbin request_path=/products upstream_url=http://httpbin.org
http POST localhost:8001/apis/httpbin/plugins name=key-auth
http POST localhost:8001/consumers username=tieske
http POST localhost:8001/consumers/tieske/key-auth key=big_secret
http GET http://localhost:8000/products apikey:big_secret
```

The final call delivers a 404 as expected.

Does your issue disappear when you restart kong (instead of deleting and recreating the api)

**Comment by anamarialazar** [comment] 2016-06-24 15:49
If I make the requests manually it works. This is not the problem.

I use kongfig in my ansbile task to apply the config. The strange part which I can explain is that all the data is in the database. Also if I make the request to get the plugins / apis / consumers, all the data is being show correctly. My issue appears when I try to use the key to query the API. Then it looks like the key-auth plugin is not being setup properly.

**Comment by Tieske** [comment] 2016-06-24 15:57
Does the issue disappear when you stop and restart kong?

**Comment by anamarialazar** [comment] 2016-06-24 16:05
No. It is still there. The only way I can get around it is to remove the api and plugin via curl and add it again. Ideally I would love to have a config file as I have quite a few APIs

**Comment by Tieske** [comment] 2016-06-24 16:07
what version of Kong and which database are you using?

**Comment by anamarialazar** [comment] 2016-06-24 16:09
0.8.3 & Postgres

**Comment by Tieske** [comment] 2016-06-24 17:30
Sorry, unable to reproduce, also with postgres. I don't know how kongfig interacts with Kong, maybe better to report the issue there.

**Comment by thefosk** [comment] 2016-07-12 02:11
Could this be a bug with Kongfig? @anamarialazar

**Comment by anamarialazar** [comment] 2016-07-12 08:55
I have raised the issue there as well but no luck...

**Comment by Tieske** [comment] 2016-07-18 10:42
any updates on this? if we can't reproduce it then I'm inclined to close it...

**Comment by anamarialazar** [comment] 2016-07-18 10:49
I have chosen to not use kongfig at the moment.

**Comment by shashiranjan84** [comment] 2016-07-29 00:11
Closing it as error not related to kong.

**Closed by shashiranjan84** 2016-07-29 00:11 UTC
