### ISSUE TITLE
Angular2 + Kong 0.9.2 (Request problem)

### ISSUE THREAD

**Issue by geazioliveira** [Mashape/kong#1712] opened 2016-10-05 17:13 UTC
Hello,

I'm developing an application in AngularJS 2 and am finding a problem using Kong. The problem is the following when I do one request for my application angle in the few moments kong does not send the content-length response and then generates an error ...

I can see the error because I made the same request without using the kong and did not have the problem.

I wonder if anyone ever had something like and how can I fix it.

Recalling that the version I'm using is 0.9.2

**Comment by thefosk** [comment] 2016-10-05 20:16
Does the final API return the `Content-Length` header?

**Comment by geazioliveira** [comment] 2016-10-14 17:27
Yes man... the API return de Content-Length header.

**Comment by thefosk** [comment] 2016-10-15 22:40
Do you see the same problem happening from a different client (ie, curl) going through Kong? Very hard to debug and reproduce this since I don't have access to the final upstream API.

**Comment by thibaultcha** [comment] 2016-11-17 21:20
Closing this from lack of update. Feel free to reopen.

**Closed by thibaultcha** 2016-11-17 21:20 UTC
Labels: question
