### ISSUE TITLE
Conflict error when creating (OAuth2) credentials multiple times in a row

### ISSUE THREAD

**Issue by dirkmoors** [Mashape/kong#478] opened 2015-08-17 14:02 UTC
See: https://circleci.com/gh/vikingco/python-kong/160

After trying to create OAuth2 credentials a few times in a row, I suddenly received the following error:
```
client_secret: client_secret already exists with value '5cb3bb2026264d60cd002603464d02d9'
client_id: client_id already exists with value 'd30db416358448ecc838bcec496905c6'
```

I specifically did not add client_id nor client_scret, so it's Kong that is generating them.
My request looks like:
```
# XXX = i++
curl -X POST http://kong:8001/consumers/{consumer_id}/oauth2 \
    --data "name=Test%20ApplicationXXX" \
    --data "redirect_uri=http://some-domain/endpointXXX/"
```

**Comment by thibaultCha** [comment] 2015-08-17 22:10
Here is my guess at what is happening here, just a feeling, I might be wrong:

We use [Tieske/uuid](https://github.com/Tieske/uuid) to generate uuids at the application level. The OAuth2 plugin was in need of randomly generated strings and it was implemented by leveraging the uuid module and simply stripping the dashes to create a random, unique string.

However, this is how the uuid module works: it needs a **seed** (passed to `math.randomseed()`) to generate unique uuids. This seeding allows `math.random()` to always return new random number. The catch is: when you seed twice with the same number, the generated random number will follow the same sequence:

```lua
math.randomseed(1) -- If 1 is given here, then subsequent calls to math.random() will always be:

math.random() -- 0.32381056237864
math.random() -- 0.013613396334358
```

To avoid that, giving `os.time()` is a common practice to have a truly unique seed and truly random numbers. Thus, calling `uuid.seed()` (like instructed) guarantees that all uuids will be unique.

**However**, I believe the following happens: each worker calls `uuid.seed()` with the current `os.time()` (or the luasocket equivalent, doesn't matter here) and thus has **the same seed**.

I believe you execute multiple calls to the admin API, and one worker takes care of them, generating new uuids. Until some point when a **new** worker handles the request. However, that new worker had the same seed, thus, the 1st uuid generated by that worker is the same uuid as the first one generated by the original worker.

To fix this, we could maybe investigate into using [lua-resty-string](https://github.com/openresty/lua-resty-string) as first advised, or find a way for each worker to truly generate unique seeds because the uuid generation also handles the entities' ids in the database.

Again, that is just a supposition at what may be happening here, this should be investigated more. TO confirm this thought I need a piece of documentation that indeed specifies that `math.randomseed()` and `math.random()` **are not** shared between all workers.
---

@dirkmoors How many requests do you make to that endpoint in your tests? Does this error happen 100% of the time?

**Comment by dirkmoors** [comment] 2015-08-18 07:31
@thibaultCha In that test, I'm posting to that endpoint 5 times. Since the error occured, I've managed to avoid it by adding delays between requests.

**Comment by Nijikokun** [comment] 2015-10-28 23:45
@thibaultCha it appears that there is a mechanism for `socket.gettime()` which provides a higher precision (ms) over `os.time()` (s) as described [here](http://tieske.github.io/uuid/). Could potentially be a solution.

Perhaps @Tieske has some input.

**Comment by Tieske** [comment] 2015-11-07 23:56
I gave this some thought and intended to comment on it just now, but my conclusion is the same as @thibaultCha the uuid module should be seeded only once, application wide. But in this case multiple processes/workers all seed on their own, causing identical seeds and hence generate identical uuid strings.

The LuaSocket solution will provide a higher time resolution and hence reduce the probability of colissions, but given a high enough load, the problem is bound to return... Cannot solve this in pure Lua with multiple processes.

Correct solution is to use an external system wide library like #695

**Comment by thefosk** [comment] 2015-11-10 02:34
#695 has been merged, and this shouldn't be an issue anymore in the next version.

**Comment by Tieske** [comment] 2015-12-14 19:46
@dirkmoors The fix was merged and released, closing this.

**Closed by Tieske** 2015-12-14 19:46 UTC
Labels: area/admin api, area/DAO, task/bug

**Comment by thibaultCha** [comment] 2015-12-14 19:49
It has actually not been released but will be soon.

**Comment by Tieske** [comment] 2015-12-15 08:30
oops my bad, thought it was in the 0.5.4 release.
