### ISSUE TITLE
Could Not Start Kong

### ISSUE THREAD

**Issue by timothyley** [Mashape/kong#1108] opened 2016-03-29 08:30 UTC
Hi, my Kong was working fine previously. However about 2 weeks ago, it started to give me error when I start Kong. I am not sure what the problem is. It gave me this error.

    dex@kongcassandra2:~$ sudo kong start
    [INFO] Kong 0.6.1
    [INFO] Using configuration: /etc/kong/kong.yml
    [INFO] database...........cassandra replication_factor=1 ssl=verify=false enabled=false data_centers=        timeout=5000 replication_strategy=SimpleStrategy contact_points=127.0.0.1:9042 keyspace=kong
    [INFO] dnsmasq............address=127.0.0.1:8053 dnsmasq=true port=8053
    [WARN] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
    [INFO] nginx .............admin_api_listen=0.0.0.0:8001 proxy_listen=0.0.0.0:80     proxy_listen_ssl=0.0.0.0:443
    [INFO] Leaving cluster..
    [ERR] Could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create     memberlist: No private IP address found, and explicit IP not provided
    [ERR] Could not start Kong
    dex@kongcassandra2:~$ 

Looking for some help please.

**Comment by thefosk** [comment] 2016-03-29 17:09
Duplicate of #1107

**Closed by thefosk** 2016-03-29 17:09 UTC

**Comment by tarunsaxenattn** [comment] 2017-01-15 04:52
The below YAML worked for me. My DNS RESOLVER Is :- 172.0.0.10
I have assigned a advertise IP to Kong :- 172.244.3.10:7946 . Before that I was facing the same problem.

apiVersion: extensions/v1beta1

kind: Deployment
metadata:
name: kong
namespace: qa
spec:
replicas: 1
strategy:
rollingUpdate:
maxSurge: 1
maxUnavailable: 0
type: RollingUpdate
template:
metadata:
labels:
run: kong
spec:
containers:
- name: kong
image: kong
imagePullPolicy: Always
ports:
- containerPort: 8000
protocol: TCP
- containerPort: 8443
protocol: TCP
- containerPort: 8001
protocol: TCP
- containerPort: 7946
protocol: UDP
- containerPort: 7946
protocol: TCP
env:
- name: KONG_DATABASE
value: postgres
- name: KONG_PG_HOST
value: xxxxxx
- name: KONG_PG_USER
value: kong
- name: KONG_PG_PASSWORD
value: password
- name: KONG_PG_DATABASE
value: kong
- name: KONG_DNS_RESOLVER
value: 172.0.0.10
- name: KONG_DNSMASQ
value: "off"
- name: KONG_CLUSTER_ADVERTISE
value: 172.244.3.10:7946
resources:
limits:
memory: 1200Mi
requests:
memory: 1100Mi

apiVersion: v1
kind: Service
metadata:
name: svc-kong
namespace: qa
annotations:
service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:xxxxxxxx:certificate/xxxxxxxxxxxxxxxxxxx
service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
ports:
- name: "www"
port: 8001
targetPort: 8001
- name: "www1"
port: 80
targetPort: 8000
- name: "https"
port: 443
targetPort: 8443

- name: "www2"

port: 7946

targetPort: 7946

selector:
run: kong
type: LoadBalancer
