### ISSUE TITLE
Possibility to config priority of plugins

### ISSUE THREAD

**Issue by t1tcrucible** [Mashape/kong#1224] opened 2016-05-17 13:28 UTC
At the moment we are facing the following issue:
When we register an API, with 2 or more authentication policies, as an example:
- key-auth (in order to retrieve the consumer == application context)
- jwt (in order to retrieve the logged-in user identity)

We see that both key-auth/jwt have priority 1000 => when using mockbin it's clear that the X-Consumer-ID/Name/... is referencing to the logged-in user (coming from JWT plugin) while we would like additionally info about the 'real' consumer application (defined by key-auth policy).

The apikey is forwarded to the upstream server, but X-Consumer headers are resolved in the context of JWT instead of key-auth. 

Is there a way to resolve AND the key-auth consumer AND the JWT consumer/user?

We thought about being able defining the priority, but we have also a situation where we would like both. 

thank you,

**Comment by Tieske** [comment] 2016-05-17 13:33
duplicate of #590?

**Comment by t1tcrucible** [comment] 2016-05-17 15:49
Yes correct! I overlooked, thank you

**Closed** 2016-05-17 16:43 UTC
Labels: BC
