### ISSUE TITLE
Kong 0.10.1 migrations failed

### ISSUE THREAD

**Issue by mgiorgio** [Mashape/kong#2390] opened 2017-04-13 19:21 UTC
### Summary

I experienced an issue when starting up Kong 0.10.1 for the very first time. Executing migrations got broken and I could only fix it by executing ```kong migrations reset``` and ```kong migrations up``` multiple times.

### Steps To Reproduce

1. Start up 3 instances of Cassandra 2.2.9
2. Start up Kong 0.10.1 ==> Sometimes it fails with the errors listed below.
3. ```kong migrations reset && kong migrations up``` ==> Sometimes it fails with below errors.

### Additional Details & Logs

- Kong version 0.10.1
- Cassandra 2.2.9 (three instances)

#### Kong debug-level startup logs (`$ kong start --vv`)
```
migrating core for keyspace kong
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [cassandra error] Error during migration 2015-01-12-175310_init_schema: [Invalid] No column definition found for column request_host
```
^ Over and over.

#### Kong Migrations (manually)
```
[root@d8744e46dea5 /]# kong migrations reset --conf /usr/local/kong/.kong_env
> Are you sure? This operation is irreversible. [Y/n] Y
Schema successfully reset
[root@d8744e46dea5 /]# kong migrations up --conf /usr/local/kong/.kong_env
migrating core for keyspace kong
core migrated up to: 2015-01-12-175310_skeleton
core migrated up to: 2015-01-12-175310_init_schema
core migrated up to: 2015-11-23-817313_nodes
core migrated up to: 2016-02-25-160900_remove_null_consumer_id
core migrated up to: 2016-02-29-121813_remove_ttls
core migrated up to: 2016-09-05-212515_retries_step_1
core migrated up to: 2016-09-05-212515_retries_step_2
core migrated up to: 2016-09-16-141423_upstreams
core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
core migrated up to: 2016-11-11-151900_new_apis_router_1
core migrated up to: 2016-11-11-151900_new_apis_router_2
core migrated up to: 2016-11-11-151900_new_apis_router_3
core migrated up to: 2017-01-24-132600_upstream_timeouts
core migrated up to: 2017-01-24-132600_upstream_timeouts_2
migrating request-transformer for keyspace kong
request-transformer migrated up to: 2016-03-10-160000_req_trans_schema_changes
migrating rate-limiting for keyspace kong
rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
rate-limiting migrated up to: 2016-07-25-471385_ratelimiting_policies
migrating hmac-auth for keyspace kong
hmac-auth migrated up to: 2015-09-16-132400_init_hmacauth
migrating jwt for keyspace kong
jwt migrated up to: 2015-06-09-jwt-auth
jwt migrated up to: 2016-03-07-jwt-alg
migrating response-ratelimiting for keyspace kong
response-ratelimiting migrated up to: 2015-08-21_init_response-rate-limiting
response-ratelimiting migrated up to: 2016-08-04-321512_response-rate-limiting_policies
migrating ip-restriction for keyspace kong
ip-restriction migrated up to: 2016-05-24-remove-cache
migrating cors for keyspace kong
cors migrated up to: 2017-03-14_multiple_orgins
migrating galileo for keyspace kong
galileo migrated up to: 2016-04-15_galileo-import-mashape-analytics
migrating acl for keyspace kong
acl migrated up to: 2015-08-25-841841_init_acl
migrating basic-auth for keyspace kong
basic-auth migrated up to: 2015-08-03-132400_init_basicauth
migrating oauth2 for keyspace kong
oauth2 migrated up to: 2015-08-03-132400_init_oauth2
oauth2 migrated up to: 2015-08-24-215800_cascade_delete_index
oauth2 migrated up to: 2016-02-29-435612_remove_ttl
Error: [cassandra error] Error during migration 2016-04-14-283949_serialize_redirect_uri: could not prepare query: [Invalid] unconfigured table oauth2_credentials

  Run with --v (verbose) or --vv (debug) for more details
```

#### Kong error logs (`<KONG_PREFIX>/logs/error.log`)
```
2017/04/13 18:58:19 [warn] 12448#0: *145 [lua] cluster.lua:745: execute(): [lua-cassandra] Aggregation query us
ed without partition key, context: ngx.timer
2017/04/13 18:58:22 [notice] 12424#0: *340 [lua] cluster.lua:688: execute(): [lua-cassandra] SELECT COUNT(*) FR
OM nodes was not prepared on host 10.192.249.5, preparing and retrying, context: ngx.timer
2017/04/13 18:58:22 [error] 12424#0: *340 [lua] cluster.lua:20: log(): [cluster] [cassandra error] could not pr
epare query: [Invalid] unconfigured table nodes, context: ngx.timer
2017/04/13 18:58:46 [error] 12437#0: *1518 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from
 datastore: [cassandra error] could not prepare query: [Invalid] unconfigured table nodes, context: ngx.timer
2017/04/13 18:59:16 [error] 12455#0: *3013 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from
 datastore: [cassandra error] could not prepare query: [Invalid] unconfigured table nodes, context: ngx.timer
2017/04/13 18:59:46 [error] 12441#0: *4509 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from
 datastore: [cassandra error] could not prepare query: [Invalid] unconfigured table nodes, context: ngx.timer
2017/04/13 19:00:16 [error] 12455#0: *6005 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from
 datastore: [cassandra error] could not prepare query: [Invalid] unconfigured table nodes, context: ngx.timer
2017/04/13 19:01:16 [notice] 12455#0: *8998 [lua] cluster.lua:688: execute(): [lua-cassandra] SELECT * FROM nod
es WHERE name = ? ALLOW FILTERING was not prepared on host 10.192.249.7, preparing and retrying, context: ngx.t
imer
2017/04/13 19:02:16 [notice] 12455#0: *11989 [lua] cluster.lua:688: execute(): [lua-cassandra] SELECT * FROM no
des WHERE name = ? ALLOW FILTERING was not prepared on host 10.192.249.6, preparing and retrying, context: ngx.
timer
```
#### Kong configuration (registered APIs/Plugins & configuration file)
Default values except for:
* anonymous_reports = off
* nginx_daemon = off
* ssl = off
* admin_ssl = off
* cluster_profile = lan

**- Operating System**
CentOS 7 in a Docker container.

**Comment by mgiorgio** [comment] 2017-04-13 19:51
By the way. After fixing this issue running ```kong migrations reset && kong migrations up``` multiple times, I started 2 extra instances of Kong, and then saw the same problem again:
```
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [cassandra error] Error during migration 2015-01-12-175310_init_schema: [Invalid] No column definition found for column request_host
```

When trying to run migrations manually:
```
[root@1aa3c8a1deb2 /]# kong migrations up --conf /usr/local/kong/.kong_env
migrating core for keyspace kong
Error: [cassandra error] Error during migration 2015-01-12-175310_init_schema: [Invalid] No column definition found for column request_host

  Run with --v (verbose) or --vv (debug) for more details
```

Could it be a race condition?

**Comment by mgiorgio** [comment] 2017-04-13 20:11
Here's something I found in errors.log in another Kong's node:
```
2017/04/13 20:07:36 [error] 32869#0: init_by_lua error: /usr/local/share/lua/5.1/kong.lua:134: [cassandra error
] Error during migration 2016-09-05-212515_retries_step_1: [Invalid] Invalid column name retries because it con
flicts with an existing column
```

It really looks like a race condition.

**Comment by thibaultcha** [comment] 2017-04-28 21:39
Should be fixed in the upcoming 0.10.2. As always, make sure you are *always* running your migrations from a *single* Kong node. No 2 Kong nodes can be started at the same time on a fresh Cassandra cluster.

**Closed by thibaultcha** 2017-04-28 21:39 UTC

**Comment by mgiorgio** [comment] 2017-04-28 21:40
Thanks @thibaultcha. Any idea when I'll be able to run migrations with multiple Kong nodes?

**Comment by thibaultcha** [comment] 2017-04-28 21:42
Probably never, due to the distributed nature of Cassandra.

**Comment by mprimeaux** [comment] 2017-05-03 17:21
I am running into this same error with Kong 0.10.2. I'll debug and report back.

**Comment by mgiorgio** [comment] 2017-05-03 17:43
@mprimeaux thanks, please report back when you get an insight. I reproduced it consistently with multiple nodes and that is considered as a known issue. I did see a problem like yours but at that point I couldn't guarantee that it was a problem with Kong itself or if it was our data centers. After that, I couldn't reproduce it anymore.

Please, let us know if you see something interesting.

**Comment by mprimeaux** [comment] 2017-05-03 19:22
Here's what I can confirm at this point in time. 

This error...

```bash
Error: [cassandra error] Error during migration 2016-11-11-151900_new_apis_router_3: [Invalid] Index 'apis_request_host_idx' could not be found in any of the tables of keyspace 'api_gateway'.
```
...only occurs the *very first* time a Kong cluster is initialised. All attempts to reproduce the same error after the initial failure using the same Kong cluster are unsuccessful. Even stopping Kong, dropping the target Cassandra keyspace, rebooting the node and attempting to run `kong start' completes execution of all migrations successfully.

Running `kong migrations reset` immediately after the initial failure does allow `kong start` to start as expected. 

Oddly enough, the only reference to "apis_request_host_idx" I can find is contained within postgres.lua, which is clearly not the configured durable storage provider.

**Comment by mgiorgio** [comment] 2017-05-03 20:30
@mprimeaux thanks for reporting back. Were you able to consistently (or, at least, multiple times) reproduce this issue? In other words, did you completely remove the Kong cluster (which, based on your previous message, is a 1-node cluster), install it again, and see this issue?

**Comment by mprimeaux** [comment] 2017-05-03 20:41
I am able to reproduce this issue consistently. I'm using Ubuntu Server 16.04 LTS. One warning I did notice when starting Kong is a message to increase ulimit to at least 4096. I'd like to investigate that next to rule it out.

**Comment by mgiorgio** [comment] 2017-05-03 20:45
Excellent, thanks for your responses. Let's wait to see what @thibaultcha and the other folks say about it.

**Comment by mprimeaux** [comment] 2017-05-03 21:04
Unfortunately, ensuring ulimit was at 4096 didn't correct the issue. 

```bash
ubuntu@ip-172-31-0-104:~$ ulimit -n 4096
ubuntu@ip-172-31-0-104:~$ ulimit
unlimited
ubuntu@ip-172-31-0-104:~$ ulimit -n
4096
ubuntu@ip-172-31-0-104:~$ kong start
migrating core for keyspace pulse_1_api_gateway
core migrated up to: 2015-01-12-175310_skeleton
core migrated up to: 2015-01-12-175310_init_schema
core migrated up to: 2015-11-23-817313_nodes
core migrated up to: 2016-02-25-160900_remove_null_consumer_id
core migrated up to: 2016-02-29-121813_remove_ttls
core migrated up to: 2016-09-05-212515_retries_step_1
core migrated up to: 2016-09-05-212515_retries_step_2
core migrated up to: 2016-09-16-141423_upstreams
core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
core migrated up to: 2016-11-11-151900_new_apis_router_1
core migrated up to: 2016-11-11-151900_new_apis_router_2
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [cassandra error] Error during migration 2016-11-11-151900_new_apis_router_3: [Invalid] Index 'apis_request_host_idx' could not be found in any of the tables of keyspace 'pulse_1_api_gateway'

  Run with --v (verbose) or --vv (debug) for more details
ubuntu@ip-172-31-0-104:~$
```

As you can see, the `ulimit` warning doesn't appear but I still experience the error.  I'll wait to hear from @thibaultcha and will continue to debug in the interim.  Please let me know if you'd like me to try anything on my end.

**Comment by mgiorgio** [comment] 2017-05-03 21:14
When I saw this issue, I was running Kong 0.9.7 and Kong 0.10.1. If you have some time and want to try with 0.10.1, it'd be great because the Kong's folks introduced some changes regarding running migrations on Cassandra.

**Comment by mprimeaux** [comment] 2017-05-03 21:15
I can confirm that I experienced this exact same error with Kong 0.10.1, which is what brought me to this thread.

**Comment by mprimeaux** [comment] 2017-05-03 21:28
...more information with `kong start --vv`.

```bash
ubuntu@ip-172-31-0-90:~$ kong start --vv
2017/05/03 21:26:35 [verbose] Kong: 0.10.2
2017/05/03 21:26:35 [debug] ngx_lua: 10007
2017/05/03 21:26:35 [debug] nginx: 1011002
2017/05/03 21:26:35 [debug] Lua: LuaJIT 2.1.0-beta2
2017/05/03 21:26:35 [verbose] reading config file at /etc/kong/kong.conf
2017/05/03 21:26:35 [debug] admin_listen = "0.0.0.0:8001"
2017/05/03 21:26:35 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/05/03 21:26:35 [debug] admin_ssl = true
2017/05/03 21:26:35 [debug] anonymous_reports = true
2017/05/03 21:26:35 [debug] cassandra_consistency = "ONE"
2017/05/03 21:26:35 [debug] cassandra_contact_points = {"172.31.26.210"}
2017/05/03 21:26:35 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/05/03 21:26:35 [debug] cassandra_keyspace = "pulse_1_api_gateway"
2017/05/03 21:26:35 [debug] cassandra_lb_policy = "RoundRobin"
2017/05/03 21:26:35 [debug] cassandra_password = "******"
2017/05/03 21:26:35 [debug] cassandra_port = 9042
2017/05/03 21:26:35 [debug] cassandra_repl_factor = 1
2017/05/03 21:26:35 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/05/03 21:26:35 [debug] cassandra_schema_consensus_timeout = 10000
2017/05/03 21:26:35 [debug] cassandra_ssl = false
2017/05/03 21:26:35 [debug] cassandra_ssl_verify = false
2017/05/03 21:26:35 [debug] cassandra_timeout = 5000
2017/05/03 21:26:35 [debug] cassandra_username = "pulse_api_gateway"
2017/05/03 21:26:35 [debug] cluster_listen = "0.0.0.0:7946"
2017/05/03 21:26:35 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/05/03 21:26:35 [debug] cluster_profile = "wan"
2017/05/03 21:26:35 [debug] cluster_ttl_on_failure = 3600
2017/05/03 21:26:35 [debug] custom_plugins = {}
2017/05/03 21:26:35 [debug] database = "cassandra"
2017/05/03 21:26:35 [debug] dns_hostsfile = "/etc/hosts"
2017/05/03 21:26:35 [debug] dns_resolver = {}
2017/05/03 21:26:35 [debug] latency_tokens = true
2017/05/03 21:26:35 [debug] log_level = "notice"
2017/05/03 21:26:35 [debug] lua_code_cache = "on"
2017/05/03 21:26:35 [debug] lua_package_cpath = ""
2017/05/03 21:26:35 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/05/03 21:26:35 [debug] lua_socket_pool_size = 30
2017/05/03 21:26:35 [debug] lua_ssl_verify_depth = 1
2017/05/03 21:26:35 [debug] mem_cache_size = "128m"
2017/05/03 21:26:35 [debug] nginx_daemon = "on"
2017/05/03 21:26:35 [debug] nginx_optimizations = true
2017/05/03 21:26:35 [debug] nginx_worker_processes = "auto"
2017/05/03 21:26:35 [debug] pg_database = "kong"
2017/05/03 21:26:35 [debug] pg_host = "127.0.0.1"
2017/05/03 21:26:35 [debug] pg_port = 5432
2017/05/03 21:26:35 [debug] pg_ssl = false
2017/05/03 21:26:35 [debug] pg_ssl_verify = false
2017/05/03 21:26:35 [debug] pg_user = "kong"
2017/05/03 21:26:35 [debug] prefix = "/usr/local/kong/"
2017/05/03 21:26:35 [debug] proxy_listen = "0.0.0.0:8000"
2017/05/03 21:26:35 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/05/03 21:26:35 [debug] serf_path = "serf"
2017/05/03 21:26:35 [debug] server_tokens = true
2017/05/03 21:26:35 [debug] ssl = true
2017/05/03 21:26:35 [debug] upstream_keepalive = 60
2017/05/03 21:26:35 [verbose] prefix in use: /usr/local/kong
2017/05/03 21:26:35 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/05/03 21:26:35 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/05/03 21:26:35 [debug] searching for OpenResty 'resty' executable
2017/05/03 21:26:35 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/05/03 21:26:35 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/05/03 21:26:35 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/05/03 21:26:35 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/05/03 21:26:35 [verbose] generating default SSL certificate and key
2017/05/03 21:26:36 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/05/03 21:26:36 [verbose] generating admin SSL certificate and key
2017/05/03 21:26:36 [verbose] running datastore migrations
2017/05/03 21:26:36 [info] migrating core for keyspace pulse_1_api_gateway
2017/05/03 21:26:36 [info] core migrated up to: 2015-01-12-175310_skeleton
2017/05/03 21:26:39 [info] core migrated up to: 2015-01-12-175310_init_schema
2017/05/03 21:26:39 [info] core migrated up to: 2015-11-23-817313_nodes
2017/05/03 21:26:39 [info] core migrated up to: 2016-02-25-160900_remove_null_consumer_id
2017/05/03 21:26:39 [info] core migrated up to: 2016-02-29-121813_remove_ttls
2017/05/03 21:26:39 [info] core migrated up to: 2016-09-05-212515_retries_step_1
2017/05/03 21:26:39 [info] core migrated up to: 2016-09-05-212515_retries_step_2
2017/05/03 21:26:40 [info] core migrated up to: 2016-09-16-141423_upstreams
2017/05/03 21:26:41 [info] core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
2017/05/03 21:26:42 [info] core migrated up to: 2016-11-11-151900_new_apis_router_1
2017/05/03 21:26:42 [info] core migrated up to: 2016-11-11-151900_new_apis_router_2
2017/05/03 21:26:42 [verbose] could not start Kong, stopping services
2017/05/03 21:26:42 [verbose] leaving serf cluster
2017/05/03 21:26:42 [verbose] left serf cluster
2017/05/03 21:26:42 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/05/03 21:26:42 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/05/03 21:26:42 [debug] no pid file at: /usr/local/kong/pids/serf.pid
2017/05/03 21:26:42 [verbose] serf agent stopped
2017/05/03 21:26:42 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [cassandra error] Error during migration 2016-11-11-151900_new_apis_router_3: [Invalid] Index 'apis_request_host_idx' could not be found in any of the tables of keyspace 'pulse_1_api_gateway'
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
ubuntu@ip-172-31-0-90:~$
```

I'll continue to investigate and report back.

**Comment by mprimeaux** [comment] 2017-05-13 03:26
Unfortunately, I've got nothing new to report. I'll continue my investigation at some point this week. Any help or insight is greatly appreciated.
