### ISSUE TITLE
Suggested Plugin : Enable/Disable API

### ISSUE THREAD

**Issue by anshulbhargava** [Mashape/kong#1837] opened 2016-11-21 10:13 UTC
Many a time it happens that a for some reasons, a particular API needs to be turned off from the outside world (say in the case of DDoS mitigation). In this scenario, if the plugin is enabled, request fired on the gateway should not be proxied to the backend and instead an error code on the lines of "Service Unavailable" must be returned. Having this plugin in place will help the DevOps by providing them a switch to enable/disable APIs. 

Please think about this feature and implement if possible :)

**Comment by pauldaustin** [comment] 2017-01-20 17:19
I would also like to see an enabled flag on the api and also an enabled flag for plugins.

In the case where an API has multiple plugins that need to be configured the initial API could be disabled. Then once all plugins have been configured the API can be enabled.

Without an enabled flag you could have the situation where the upstream server could be accessed for a brief period of time without the appropriate authentication plugins configured.

I'll see if I can come up with a pull request for this feature.

**Comment by pauldaustin** [comment] 2017-01-23 20:19
Duplicate of #1279

**Comment by p0pr0ck5** [comment] 2017-06-13 15:50
Closing as a dup.

**Closed by p0pr0ck5** 2017-06-13 15:50 UTC
