### ISSUE TITLE
Inconsistent `created_at` Timestamp Formats

### ISSUE THREAD

**Issue by plukevdh** [Mashape/kong#1542] opened 2016-08-24 18:03 UTC
### Summary

When attempting to `PUT` against an existing API definition via the management API, the timestamp format for the `created_at` field is not consistent with the one required for `POST`.

This likely affects other endpoints as well (Plugins, ACLs, etc).
### Steps To Reproduce

Please see https://github.com/plukevdh/kong-fail for a self-contained instance with steps to reproduce issue seen.
### Additional Details & Logs
- Kong version (`0.8.3`)
- Kong configuration (included in the issue repo above)
- Kong error logs mostly concerned with `2016/08/24 17:20:17 [error] 101#0: *35 [lua] responses.lua:99: handler(): ERROR: column "created_at" is of type timestamp without time zone but expression is of type integer (215), client: 192.168.99.1, server: , request: "POST /apis HTTP/1.1",` (also see live logs from issue repo)
- Operating System: Docker/Linux

**Comment by thefosk** [comment] 2016-08-24 18:06
@plukevdh can you try to replicate this with latest v0.9?

**Comment by plukevdh** [comment] 2016-08-24 18:28
Will do. I think there are config format changes that will take me a bit to resolve.

**Comment by plukevdh** [comment] 2016-08-24 19:01
@thefosk the error continues to occur on 0.9.0. I will update the repo scripts to use 0.9.0

**Comment by plukevdh** [comment] 2016-08-24 19:11
Seeing another failure that I need resolution on first before these updates will work: https://github.com/Mashape/kong/issues/1543

**Comment by thefosk** [comment] 2016-08-29 18:14
@plukevdh #1543 has been resolved.

**Comment by thefosk** [comment] 2016-08-29 18:58
@plukevdh can you send me an example of a timestamp that fails? Are you using Cassandra or Postgres?

**Comment by plukevdh** [comment] 2016-08-29 21:09
Postgres. 

@thefosk I can. The linked repo also has reproducible example steps including the timestamp formats.

Successful create (`POST`):
```
curl -X "POST" "http://${DOCKER_IP}:8001/apis" \
	  -H "Content-Type: application/json" \
	  -d "{\"created_at\":\"now\",\"name\":\"profiles\",\"request_path\":\"/profiles\",\"strip_request_path\":true,\"upstream_url\":\"http://profiles.com/profiles\"}"
```

Update with failure (`PUT`):
```
curl -X "PUT" "http://${DOCKER_IP}:8001/apis" \
 	  -H "Content-Type: application/json" \
	  -d "{\"created_at\":\"now\",\"id\":\"${API_ID}\",\"name\":\"profiles\",\"request_path\":\"/profiles\",\"strip_request_path\":true,\"upstream_url\":\"http://profiles.priv/priv/profiles\"}"
```

In both cases, I am using `"created_at": "now"`.

**Comment by thefosk** [comment] 2016-08-29 22:14
@plukevdh I haven't run the commands yet but I guess the cause of the issue is that you need to specify a numeric timestamp, instead of the `now` string. With `POST` the error doesn't happen because we override `created_at` anyways.

**Comment by thefosk** [comment] 2016-09-08 16:26
@plukevdh have you tried with a number timestamp? I will go ahead and close this issue - please let me know if the problem still happens with a numeric timestamp.

**Comment by plukevdh** [comment] 2016-09-08 16:36
I can see from your response that you have not looked at the details that I provided in the sample repo. Yes I have tried and yes it works. The issue is not that there isn't a format that works, it's that the POST vs PUT requests take different formats.

**Comment by thibaultcha** [comment] 2016-09-08 16:48
(I think we should keep this open and classify this as a bug)

**Comment by thefosk** [comment] 2016-09-08 17:00
I don't think it's a bug at all. `created_at` is a timestamp in a numeric format. When you create a new entity with `"created_at": "now"`, the value `now` is a string value, not a timestamp.

**Comment by plukevdh** [comment] 2016-09-08 17:08
@thefosk "now" translates to the current time in PG.

**Comment by thibaultcha** [comment] 2016-09-08 17:11
Since we maintain a pluggable backend architecture and because of consistency (between different datastores and responses from the API) semantics, I would rather make the API only accept numerical timestamp values. The fact that the admin API is accepting "now" is what I would consider to be the bug here.

**Comment by Tieske** [comment] 2016-09-08 17:57
> The fact that the admin API is accepting "now" is what I would consider to be the bug here.

:+1:

**Closed** 2017-03-08 01:10 UTC
Labels: task/bug
