### ISSUE TITLE
 KONG add a slash at the end of URL in the version of 0.10x

### ISSUE THREAD

**Issue by ssholder** [Mashape/kong#2274] opened 2017-03-28 07:20 UTC
###Summary

 When I access one of my services like http:// example.com/service.controller through the browser,
 the browser give me the right data and return the HTTP status code 200 OK, but when I add a slash at the 
end of that url, that is to say the url is http:// example.com/service.controller/, the browser return the HTTP 
status code 404 NOT FOUND and I don't receive the right data which I want to get. If I want to get the right 
data from the service when I access the url, I should not add the slash at the end of that url.

### Steps To Reproduce
When I register an API like

name: test1
upstream_url: 'http:// example.com/service.controller'
uris:'/test1'
Then access the API by curl：curl -X GET http://kong:8000/test1.
Unfortunately，It return HTTP status code 404 NOT FOUND. Why? Because KONG add a slash at the end of upstream_url, I can't get the right data.
When I use the vesion of 0.9x, I can get the right result, because KONG don't add a slash at the end.
So, how to fix that bug？ Look forward to the next version or we can configure some parameters to avoid the slash at the end?

**Comment by bungle** [comment] 2017-03-28 12:08
Duplicate of #2211.

**Closed by bungle** 2017-03-28 12:08 UTC
