### ISSUE TITLE
Kong request size limit configuration off by a factor of 10

### ISSUE THREAD

**Issue by atcollins06** [Mashape/kong#1421] opened 2016-07-19 02:54 UTC
### Summary

The Kong Request Size Limiting plugin allows you to configure the value to use to limit the size of requests.  The stated units in the documentation are MB.  However, the code is off by a factor of 10 when configuring the size.

### Steps To Reproduce

1.  Configure size limit to .01.  This should limit the size to 10KB
2. Send a request with a size of more that 1KB but less than 10KB
3. Request will be rejected due to exceeding size limit

### Additional Details & Logs

- Kong version 0.8.3
- Kong configuration (Kong Request Size Limiting Plugin with config.allowed_payload_size=0.01)
- Kong error logs N/A
- Operating System N/A

You can see the error at line 15 of master/kong/plugins/request-size-limiting/handler.lua:

local allowed_bytes_size = allowed_size * 100000

That should be multiplied by 1000000, not 100000 (missing a 0).  Actually, the computer scientist in me says the value should really be multiplied by 1048576, not 1000000.

**Comment by Tieske** [comment] 2016-07-19 06:18
duplicate of #1415

**Closed by Tieske** 2016-07-19 06:18 UTC
