### ISSUE TITLE
Unable to start, Error:serf_signals.lua:59 ... serf_compatible

### ISSUE THREAD

**Issue by aniceday** [Mashape/kong#2217] opened 2017-03-17 06:37 UTC
### Summary
when i run `/usr/local/bin/kong start -c /etc/kong/kong.conf.default`
#### details:
ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
migrating core for database kong
core migrated up to: 2015-01-12-175310_skeleton
core migrated up to: 2015-01-12-175310_init_schema
core migrated up to: 2015-11-23-817313_nodes
core migrated up to: 2016-02-29-142793_ttls
core migrated up to: 2016-09-05-212515_retries
core migrated up to: 2016-09-16-141423_upstreams
core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
core migrated up to: 2016-11-11-151900_new_apis_router_1
core migrated up to: 2016-11-11-151900_new_apis_router_2
core migrated up to: 2016-11-11-151900_new_apis_router_3
core migrated up to: 2016-01-25-103600_unique_custom_id
core migrated up to: 2017-01-24-132600_upstream_timeouts
core migrated up to: 2017-01-24-132600_upstream_timeouts_2
migrating key-auth for database kong
key-auth migrated up to: 2015-07-31-172400_init_keyauth
migrating galileo for database kong
galileo migrated up to: 2016-04-15_galileo-import-mashape-analytics
migrating acl for database kong
acl migrated up to: 2015-08-25-841841_init_acl
migrating ip-restriction for database kong
ip-restriction migrated up to: 2016-05-24-remove-cache
migrating hmac-auth for database kong
hmac-auth migrated up to: 2015-09-16-132400_init_hmacauth
migrating jwt for database kong
jwt migrated up to: 2015-06-09-jwt-auth
jwt migrated up to: 2016-03-07-jwt-alg
migrating oauth2 for database kong
oauth2 migrated up to: 2015-08-03-132400_init_oauth2
oauth2 migrated up to: 2016-07-15-oauth2_code_credential_id
oauth2 migrated up to: 2016-12-22-283949_serialize_redirect_uri
oauth2 migrated up to: 2016-09-19-oauth2_api_id
oauth2 migrated up to: 2016-12-15-set_global_credentials
migrating basic-auth for database kong
basic-auth migrated up to: 2015-08-03-132400_init_basicauth
basic-auth migrated up to: 2017-01-25-180400_unique_username
migrating response-ratelimiting for database kong
response-ratelimiting migrated up to: 2015-08-03-132400_init_response_ratelimiting
response-ratelimiting migrated up to: 2016-08-04-321512_response-rate-limiting_policies
migrating rate-limiting for database kong
rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
rate-limiting migrated up to: 2016-07-25-471385_ratelimiting_policies
31 migrations ran
#### Error: /usr/local/share/lua/5.1/kong/cmd/utils/serf_signals.lua:59: attempt to concatenate upvalue 'serf_compatible' (a table value)

  Run with --v (verbose) or --vv (debug) for more details

#### /usr/local/bin/kong start -c /etc/kong/kong.conf.default --vv
2017/03/17 06:34:06 [verbose] running datastore migrations
2017/03/17 06:34:06 [verbose] migrations up to date
2017/03/17 06:34:06 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2017/03/17 06:34:06 [debug] searching for 'serf' executable
2017/03/17 06:34:06 [debug] serf version: ''
2017/03/17 06:34:06 [debug] Serf executable not found at serf
2017/03/17 06:34:06 [verbose] could not start Kong, stopping services
2017/03/17 06:34:06 [verbose] leaving serf cluster
2017/03/17 06:34:06 [verbose] left serf cluster
2017/03/17 06:34:06 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/03/17 06:34:06 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/03/17 06:34:06 [debug] no pid file at: /usr/local/kong/pids/serf.pid
2017/03/17 06:34:06 [verbose] serf agent stopped
2017/03/17 06:34:06 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/utils/serf_signals.lua:59: attempt to concatenate upvalue 'serf_compatible' (a table value)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:40: in function <init_worker_by_lua:38>
	[C]: in function 'pcall'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>

### Additional Details & Logs

- Kong version (`0.10.0`)

**Comment by Tieske** [comment] 2017-03-17 07:56
thx for the report. The problem is that Kong cannot find Serf (a dependency). But printing the error message generates the error.

The error you should have gotten is; `could not find 'serf' executable. Kong requires version 0.7.0 to 0.8.1 (you can tweak 'serf_path' to your needs)`

hth

**Comment by Tieske** [comment] 2017-03-17 08:09
fix is in #2218, closing this.

**Closed by Tieske** 2017-03-17 08:09 UTC

**Comment by aniceday** [comment] 2017-03-17 09:08
@Tieske tks~ 
I run`export KONG_SERF_PATH="/usr/local/bin/serf"` ,then it's works!
By the way, it's also works by setting `/usr/local/bin/` in PATH .

**Comment by manyixu** [comment] 2017-04-04 10:52
0.10 version still generating this error
 Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: could not find 'serf' executable. Kong requires version 0.7.0 to 0.8.1 (you can tweak 'serf_path' to your needs)

**Comment by Tieske** [comment] 2017-04-05 08:52
@manyixu that is the correct error, and you can, as suggested in the message, tweak the `serf_path` setting.
