### ISSUE TITLE
request_path match order

### ISSUE THREAD

**Issue by y-zono** [Mashape/kong#2242] opened 2017-03-23 02:46 UTC
I have some api endpoints and I want enable plugin on specific endpoint. I'm wondering how request_path matching works.

Take for the following example, I have two api settings; "api-item" and "api-all". I want to setup hmac plugin for only "api-item".

```
e.g. my expectation

GET http://api.sample.com/v1/items <= HMAC enabled
GET http://api.sample.com/v1/items/001 <= HMAC enabled
POST http://api.sample.com/v1/items <= HMAC enabled
GET http://api.sample.com/v1/employees <= HMAC disabled
GET http://api.sample.com/v1/customers <= HMAC disabled
```

After testing, it worked as my expectation. I think request_path priorities longer match. Is this my understanding correct?

```
* API List

curl -i -X GET \
  --url http://localhost:8001/apis/

{
  "data": [
    {
      "upstream_url": "http://api.sample.com/",
      "request_path": "/v1/items",
      "id": "6ac62668-09b6-4182-bee0-0cc5cb5d8d0d",
      "created_at": 1490233548000,
      "preserve_host": false,
      "strip_request_path": false,
      "name": "api-item"
    },
    {
      "upstream_url": "http://api.sample.com/",
      "request_path": "/v1",
      "id": "eb55641b-56f5-43a9-b976-9f912d850a41",
      "created_at": 1490234676000,
      "preserve_host": false,
      "strip_request_path": false,
      "name": "api-all"
    }
  ],
  "total": 2
}

* Plugin

curl -i -X GET \
    --url http://localhost:8001/apis/api-item/plugins/ \
    --data "name=hmac-auth"

{
  "api_id": "6ac62668-09b6-4182-bee0-0cc5cb5d8d0d",
  "id": "16eb69e3-14c8-41d2-a104-7f50b03ac1bb",
  "created_at": 1490233737000,
  "enabled": true,
  "name": "hmac-auth",
  "config": {
    "hide_credentials": false,
    "clock_skew": 300
  }
}
```

**Comment by y-zono** [comment] 2017-03-23 03:24
I searched keyword 'request_path' on the github repo but I couldn't find the source code of the matching process. I would be grateful if you can share the code so that I can see the process.

**Comment by therealgambo** [comment] 2017-03-23 03:41
Looks like a duplicate of https://github.com/Mashape/kong/issues/677

**Comment by therealgambo** [comment] 2017-03-23 03:45
This PR https://github.com/Mashape/kong/pull/1970 documents the way the selection is done for versions >= 0.10.0.

**Comment by y-zono** [comment] 2017-03-23 03:59
Thank you. I'm reading it now.
My kong is now version 0.9.9.

**Comment by y-zono** [comment] 2017-03-23 04:11
>The rule is that : when evaluating a request, Kong will first try to match the APIs with the most rules.
>https://getkong.org/docs/0.10.x/proxy/#routing-priorities

It seems my understanding is correct. And I think that combining request_path and request_host became possible from version 0.10. Awesome. https://github.com/Mashape/kong/issues/845

**Comment by Tieske** [comment] 2017-03-24 14:46
before 0.10 the paths would be matched longest to shortest. So you are correct. In 0.10 it was rewritten, haven't checked, but assume that it still works the same way.

In general: the more specific match has a higher precedence

**Closed by Tieske** 2017-03-24 14:46 UTC
