### ISSUE TITLE
[ip-restriction] Internal Server Error

### ISSUE THREAD

**Issue by Toilal** [Mashape/kong#782] opened 2015-12-06 13:10 UTC
I have defined `ip-restriction` resulting in this configuration.

```
      "api_id": "7a6f3a89-cacc-4dfa-cdff-220757de3ff9",
      "id": "26406d36-6a72-4a5c-ca04-b1e57e551afd",
      "created_at": 1449406775000,
      "enabled": true,
      "name": "ip-restriction",
      "config": {
        "whitelist": [
          "172.17.0.1"
        ]
      }
```

When I try to access the API, It fails with an internal server (500) and this traceback in `error.log`

```
60#0: *477 lua entry thread aborted: runtime error:
/usr/local/share/lua/5.1/resty/iputils.lua:178: bad argument #1 to 'ipairs' (tab
le expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'ipairs'
        /usr/local/share/lua/5.1/resty/iputils.lua:178: in function 'ip_in_cidrs
'
        ...cal/share/lua/5.1/kong/plugins/ip-restriction/access.lua:17: in funct
ion 'execute'
        ...al/share/lua/5.1/kong/plugins/ip-restriction/handler.lua:18: in funct
ion 'access'
        /usr/local/share/lua/5.1/kong.lua:191: in function 'exec_plugins_access'
        access_by_lua(nginx.conf:91):1: in function <access_by_lua(nginx.conf:91
):1>, client: 172.17.0.1, server: _, request: "GET /?filename=test.avi HTTP/1.1"
, host: "api.guessit.io"
2015/12/06 13:00:31 [error] 60#0: *477 [lua] responses.lua:61: send_HTTP_INTERNA
L_SERVER_ERROR(): An unexpected error occurred, client: 172.17.0.1, server: _, r
equest: "GET /?filename=test.avi HTTP/1.1", host: "api.guessit.io"
```

I run Kong `0.5.4` using docker:

```
{
  "version": "0.5.4",
  "lua_version": "LuaJIT 2.1.0-alpha",
  "tagline": "Welcome to Kong",
  "hostname": "8df968227cd6",
  "plugins": {
    "enabled_in_cluster": [
      "ip-restriction",
      "key-auth"
    ],
    "available_on_server": [
      "ssl",
      "jwt",
      "acl",
      "cors",
      "oauth2",
      "tcp-log",
      "udp-log",
      "file-log",
      "http-log",
      "key-auth",
      "hmac-auth",
      "basic-auth",
      "ip-restriction",
      "mashape-analytics",
      "request-transformer",
      "response-transformer",
      "request-size-limiting",
      "rate-limiting",
      "response-ratelimiting"
    ]
  }
}
```

**Comment by thibaultCha** [comment] 2016-01-14 04:40
I could not reproduce this but I added a check just in case in #878.

**Comment by thefosk** [comment] 2016-02-03 00:02
@Toilal can you try this with the new 0.6.0 version? Just make sure that you follow the upgrade path to 0.6.0 since it introduces some breaking changes.

**Comment by Toilal** [comment] 2016-02-03 07:25
It seems this version is not available on Docker hub. I really need this before installing it.

**Comment by thibaultCha** [comment] 2016-02-03 07:26
0.6.0 is on Dockerhub: https://hub.docker.com/r/mashape/kong/

**Comment by Toilal** [comment] 2016-02-03 07:29
It's in the README, but doesn't appear as a tag in this page. https://hub.docker.com/r/mashape/kong/tags/

And i actually pulled the image, it's still grab 0.5.4. 0.6.0rc3 is available, but not final. I'll try to build image myself though.

**Comment by thibaultCha** [comment] 2016-02-03 07:30
I see it in the list of tags though

**Comment by Toilal** [comment] 2016-02-03 07:35
Ho yes, you are right ! Damn docker hub UI, all tags are disordered :)

But there's still a problem with `latest`, which is still 2 month old ... It works if I pull `mashape/kong:0.6.0` explicitly, but when pulling mashape/kong I still get `0.5.4`.

**Comment by thibaultCha** [comment] 2016-02-03 07:39
Oh indeed, it seems Docker did not trigger the build when master was pushed for 0.6.0...

**Comment by thefosk** [comment] 2016-02-03 08:07
@Toilal can you try again to pull `latest` - I re-triggered the build.

**Comment by Toilal** [comment] 2016-02-04 17:24
I experienced deployement issues with 0.6.0, but now all is deploying great with 0.6.1. I'll build my configuration an try ip_restriction feature ... stay tuned, thanks :)

**Comment by thefosk** [comment] 2016-02-04 19:51
Nice - I will close this now. Feel free to reopen if the problem persists.

**Comment by Toilal** [comment] 2016-02-04 22:01
First of all, it seems that this plugin requires a restart of kong for new configuration to be effective. This detail is either a bug, or either lacking from docs (https://getkong.org/plugins/ip-restriction/#configuration).

Then, it blocks unauthorized IP trying to access the API properly. But with an authorized IP, it crash with the following error log: 

```
kong_1         | 2016/02/04 21:56:30 [error] 62#0: *114 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/iputils.lua:179: attempt to compare nil with number
kong_1         | stack traceback:
kong_1         | coroutine 0:
kong_1         | 	/usr/local/share/lua/5.1/resty/iputils.lua: in function 'ip_in_cidrs'
kong_1         | 	...al/share/lua/5.1/kong/plugins/ip-restriction/handler.lua:31: in function 'access'
kong_1         | 	/usr/local/share/lua/5.1/kong.lua:166: in function 'access'
kong_1         | 	access_by_lua(nginx.conf:92):1: in function <access_by_lua(nginx.conf:92):1>, client: 87.231.4.32, server: _, request: "GET /favicon.ico HTTP/1.1", host: "kong.admin.xxxxxx.com:8000", referrer: "http://kong.admin.xxxxxx.com:8000/"
kong_1         | 2016/02/04 21:56:30 [error] 62#0: *114 [lua] responses.lua:97: send_HTTP_INTERNAL_SERVER_ERROR(): An unexpected error occurred, client: 87.231.4.32, server: _, request: "GET /favicon.ico HTTP/1.1", host: "kong.admin.xxxxxx.com:8000", referrer: "http://kong.admin.xxxxxx.com:8000/"
```

This is the plugin configuration

```
{
  "data": [
    {
      "api_id": "8f59cdd3-f136-4f6a-8511-8faf22f975a5",
      "id": "3255c75e-4433-4d85-8a5a-97079a220bd9",
      "created_at": 1454621178000,
      "enabled": true,
      "name": "ip-restriction",
      "config": {
        "_whitelist_cache": [
          "1474757665",
          "1474757665"
        ],
        "whitelist": [
          "xxx.xxx.xxx.xxx" // My own public IP address here
        ]
      }
    }
  ],
  "total": 1
}
```

**Comment by thefosk** [comment] 2016-02-04 22:25
Thanks for the logs - let me look into this. I will try to reproduce these problems in a test case.

**Comment by thefosk** [comment] 2016-02-06 00:01
@Toilal I have an update for this issue. It seems like the restart problem was caused by a bug, which PR #960 fixes.

Regarding the stack trace, I still don't know why it happens but the PR adds a check and blocks requests from [unix domain sockets](https://en.wikipedia.org/wiki/Unix_domain_socket) which are not supported.

**Comment by thefosk** [comment] 2016-02-25 22:53
@Toilal could you try again with Kong v0.7.0?

**Comment by thefosk** [comment] 2016-03-11 01:29
@Toilal just a little ping to make sure this issue is indeed fixed.

**Comment by Toilal** [comment] 2016-03-14 07:58
I'm sorry, don't have time to test this now. I'll try to test during the week.

**Closed** 2016-04-11 05:03 UTC
Labels: area/plugins, task/bug
