### ISSUE TITLE
Kong Nodes down 0.10.1 and fails to restart

### ISSUE THREAD

**Issue by harryparmar** [Mashape/kong#2507] opened 2017-05-09 15:30 UTC
*Note: GitHub issues should be reserved only for bug reports. Please use the
[Kong mailing list](https://groups.google.com/forum/#!forum/konglayer) or
[Gitter](https://gitter.im/Mashape/kong) for user support, development
questions, feature requests, etc.*

### Summary

Kong nodes 0.10.1 are in error state and trying to restart fails

### Steps To Reproduce

1. When trying to access any api through port 8000 gives message {
"message": "An unexpected error occurred"
}
2. trying to access port 8001 gives same message.
3. trying to restart nodes fails 
4.

### Additional Details & Logs

- Kong version (`0.10.1`)
- Kong debug-level startup logs (`$ kong start --vv`)
cat: /usr/local/kong/pids/nginx.pid: No such file or directory
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: 

  Run with --v (verbose) or --vv (debug) for more details
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: 

  Run with --v (verbose) or --vv (debug) for more details
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: 

  Run with --v (verbose) or --vv (debug) for more details
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: 

  Run with --v (verbose) or --vv (debug) for more details
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: 

  Run with --v (verbose) or --vv (debug) for more details
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: 

  Run with --v (verbose) or --vv (debug) for more details
Error: [cassandra error] no release_version for peer 10.230.11.13

  Run with --v (verbose) or --vv (debug) for more details
Error: [cassandra error] no release_version for peer 10.230.11.13

  Run with --v (verbose) or --vv (debug) for more details
Error: [cassandra error] no release_version for peer 10.230.11.13

  Run with --v (verbose) or --vv (debug) for more details
Error: [cassandra error] no release_version for peer 10.230.11.13

  Run with --v (verbose) or --vv (debug) for more details
Error: [cassandra error] no release_version for peer 10.230.11.13

  Run with --v (verbose) or --vv (debug) for more details
Error: [cassandra error] no release_version for peer 10.230.11.13

  Run with --v (verbose) or --vv (debug) for more details- Kong error logs 

(`<KONG_PREFIX>/logs/error.log`)
2017/05/09 15:26:35 [error] 58#0: *79079721 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.14, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:37 [error] 57#0: *79099510 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.15, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:40 [error] 58#0: *79079721 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.14, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:42 [error] 58#0: *79079721 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.15, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:45 [error] 58#0: *79079721 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.14, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:47 [error] 57#0: *79099510 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.15, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:50 [error] 58#0: *79079721 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.14, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:52 [error] 57#0: *79099510 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.15, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:55 [error] 57#0: *79099510 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.14, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:26:57 [error] 57#0: *79099510 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.15, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:27:00 [error] 57#0: *79099510 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.14, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:27:02 [error] 57#0: *79130512 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, context: ngx.timer
2017/05/09 15:27:02 [error] 58#0: *79079721 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.15, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:27:05 [error] 57#0: *79099510 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host still considered down, client: 10.230.8.14, server: kong_admin, request: "GET / HTTP/1.1", host:
"localhost:8001"
2017/05/09 15:27:07 [warn] 58#0: *79079721 [lua] cluster.lua:136: set_peer_down(): [lua-cassandra] setting host at 10.230.11.13 DOWN, client: 10.230.8.15, server: kong_admin, request: "GET / HTTP/1.1", host: "localhost:8001"
2017/05/09 15:27:07 [error] 58#0: *79079721 [lua] responses.lua:101: [cassandra error] all hosts tried for query failed. 10.230.11.13: host seems unhealthy, considering it down (connection refused), client: 10.230.8.15, server: kong_admi
n, request: "GET / HTTP/1.1", host: "localhost:8001"

- Kong configuration (registered APIs/Plugins & configuration file)

- Operating System
Centos 7.2.1511

**Comment by p0pr0ck5** [comment] 2017-05-09 15:36
Closing as a duplicate of Gitter chatter, noted in https://gitter.im/Mashape/kong?at=5911e1a0d1a7716a0aab7979

**Closed by p0pr0ck5** 2017-05-09 15:36 UTC
