### ISSUE TITLE
Various ways to apply plugins

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#486] opened 2015-08-18 21:07 UTC
Currently the only current way to apply a plugin is by associating it with an API. This doesn't work well with my real world use cases as sometimes an API will have a lot of separate functionality that would benefit from their own specific plugins and plugin configurations. Nginx handles this by having `contexts` for their directives, where you can apply or overwrite a directive in `http`, `server`, or `location` blocks, and also allowing some directives to only apply based on certain header values.

Here are some ways that could be used to assign plugin functionality to incoming requests:

- Globally (this would apply to all APIs)
- By API (What we currently have)
  - By Endpoint (https://github.com/Mashape/kong/issues/160)
  - By Method (https://github.com/Mashape/kong/issues/160)
  - By Request Header (`Accept`, `Content-Type`, `User-Agent`, etc...)
- By Consumer 

Additionally endpoint and request headers would need regex or wildcard support to be very useful.

**Comment by thibaultCha** [comment] 2015-08-18 21:12
This is a duplicate of other issues already discussing that

**Comment by montanaflynn** [comment] 2015-08-18 21:56
Which issues? I only found #160

**Comment by montanaflynn** [comment] 2015-08-18 22:07
So I also found https://github.com/Mashape/kong/issues/295 which is about applying a global plugin and also mentions applying to Consumers. In any case, both #160 and #295 are not included in any milestones and are unclear (#160 title is for endpoints, but methods are brought up, #295 title is for global but brings up consumers...) so it might be good to have a single issue or place to discuss the best strategy for handling the assignment of plugins in Kong.

**Comment by thefosk** [comment] 2015-08-25 20:31
Closed in favor of #505.

**Closed by thefosk** 2015-08-25 20:31 UTC
Labels: duplicate
