### ISSUE TITLE
0.9 doesn't resolve hostnames when connecting to the database

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1523] opened 2016-08-19 05:08 UTC
### Summary

Kong 0.9 doesn't properly resolve DNS addresses when connecting to the database.

### Steps To Reproduce

With Postgres running locally, first try:

```shell
KONG_PG_HOST=127.0.0.1 bin/kong start
```
and it works. But then try:

```shell
KONG_PG_HOST=localhost bin/kong start
```
and it doesn't work.

### Additional Details & Logs

Make sure you have an entry in `/etc/hosts` for `localhost`.

**Comment by thefosk** [comment] 2016-08-19 05:54
This was working in 0.8.3

**Comment by Tieske** [comment] 2016-08-19 08:32
can't reproduce;

```
Mashapes-MacBook-Pro-2:kong thijs$ kong stop
Kong stopped
Mashapes-MacBook-Pro-2:kong thijs$ export KONG_DATABASE=postgres
Mashapes-MacBook-Pro-2:kong thijs$ export KONG_PG_HOST=localhost
Mashapes-MacBook-Pro-2:kong thijs$ kong start
Kong started
Mashapes-MacBook-Pro-2:kong thijs$ kong stop
Kong stopped
Mashapes-MacBook-Pro-2:kong thijs$ export KONG_DATABASE=cassandra
Mashapes-MacBook-Pro-2:kong thijs$ export KONG_CASSANDRA_CONTACT_POINTS=localhost
Mashapes-MacBook-Pro-2:kong thijs$ kong start
Kong started
Mashapes-MacBook-Pro-2:kong thijs$
```

**Comment by thefosk** [comment] 2016-08-19 18:00
It only happens with Postgres, and not with Cassandra.

**Comment by thibaultcha** [comment] 2016-08-19 19:21
I'm seeing the same behavior, however I don't understand why that would not happen for Cassandra either.

**Comment by thefosk** [comment] 2016-08-19 21:52
We find out the problem was in the fact that we are invoking Kong with `resty` as opposed to using `luajit` like we did in 0.8.3.

**Comment by thibaultcha** [comment] 2016-08-19 22:06
With https://github.com/thibaultcha/lua-resty-socket/pull/9 we'll give the possibility to disable cosocket support in some contexts, forcing resty-cli's `timer` context to use LuaSocket, hence allowing us to resolve `/etc/hosts` hostnames. It also improves support for cosockets compatibility, hence we'll be able to use it in pgmoon as well.

Long term, it should probably be cleaner if resty-cli would support resolving `/etc/hosts` hostnames via some hijacking of the `tcpsock:connect` method.

**Closed** 2016-08-20 00:40 UTC

**Comment by Tieske** [comment] 2016-08-21 20:12
@thibaultcha 

> I'm seeing the same behavior, however I don't understand why that would not happen for Cassandra either.

Isn't this code; https://github.com/Mashape/kong/commit/eba2d904509ed64deb1e69a75ed6a7625a16313f#commitcomment-18712628

the reason Cassandra does work, where Postgres fails. And if so, doesn't this mean that Cassandra is NOT using co-sockets at all?

**Comment by thibaultcha** [comment] 2016-08-21 20:15
No, Cassandra is, even with this code. 

I will explain both the edge-case that person commented on and this issue on Monday.

**Comment by tsing** [comment] 2017-01-24 16:03
0.10.0rc2 has this problem too, it happens Postgres and Cassandra.

**Comment by thibaultcha** [comment] 2017-01-24 19:49
With 0.10.0rc2, I am able to run:
```
$ KONG_PG_HOST=localhost kong start
Kong started
```

and: 
```
$ KONG_DATABASE=cassandra KONG_CASSANDRA_CONTACT_POINTS=localhost kong start
Kong started
```

Without any issue.

**Comment by tsing** [comment] 2017-02-09 07:22
@thibaultcha figured out the problem.

It was caused by the configuration of our internal skydns. The database domain has an SRV and A record such as:

`postgres.internal.local SRV 10 100 1 postgres.internal.local`
`postgres.internal.local A 192.168.100.3`

It seems that kong will try to resolve the SRV record with point to the domain itself and failed.
