### ISSUE TITLE
recommended way to Cache responses from Kong?

### ISSUE THREAD

**Issue by maestr0** [Mashape/kong#1016] opened 2016-02-24 16:39 UTC
What is the recommended way to cache responses from Kong?
Does Kong support response caching? Is there any production ready plugin which can do it?

I could probably use Varnish in front of Kong, but I'm looking for a solution I could control from my Kong cluster directly.

Kong architecture diagram shows Caching as one of the features. How is this supposed to work?

![Kong architecture diagram](http://cl.ly/image/1B3J3b3h1H1c/Image%202015-07-07%20at%206.57.25%20PM.png)

**Comment by thefosk** [comment] 2016-02-25 09:14
Currently we recommend leveraging the underlying nginx server to achieve this, with the `proxy_cache` directive (you will need to manually change the `nginx` property into `kong.yml`). A more Kong-esque way of doing this would be to create a caching plugin, like #42 suggests.

**Comment by thefosk** [comment] 2016-02-26 01:26
I will close as duplicate of the mentioned issues.

**Closed by thefosk** 2016-02-26 01:26 UTC

**Comment by itaimalek** [comment] 2018-08-13 16:13
Hi guys, 
so, I'm trying to configure caching with kong.yml as suggested by @thefosk 
Nginx configurations added are:
```
proxy_cache_path /etc/nginx/cache/getuser keys_zone=getuser:5m;
proxy_cache_path /etc/nginx/cache/pasauth keys_zone=pasauth:5m;
proxy_cache_methods GET HEAD POST;
```
beginner question: how do I configure my route/service to use those directives?
