### ISSUE TITLE
Create api with a dynamic id

### ISSUE THREAD

**Issue by dzung1nguyen** [Mashape/kong#2276] opened 2017-03-28 07:42 UTC
Hi guys,

Can you help me create API with dynamic id?

GET: 
example.com/products/12
=> my.api.com/products/12

example.com/products/14
=> my.api.com/products/14

I am using Kong 0.10.0

Thank you.

**Comment by coopr** [comment] 2017-03-28 14:24
Closing as duplicate of #677

**Closed by coopr** 2017-03-28 14:24 UTC

**Comment by Tieske** [comment] 2017-03-28 14:51
as a side not: in this case (parameter is the last part) you could set up an api with just a hostname or the path up to the parameter. That would work.
