### ISSUE TITLE
Having multiple upstreams for single API endpoint in Kong

### ISSUE THREAD

**Issue by harryparmar** [Mashape/kong#1129] opened 2016-04-06 15:18 UTC
Hi

I have question, I want to achieve if upstream route A is down automatically forward request to Route B. Is this possible? will this be achieved with https://github.com/Mashape/kong/issues/157
Any ideas when will this be implemented?
Been testing Kong and really like it. One thing I want to point out is Runscope plugin is prominently displayed in your Quickstart but config for it is missing in Constants.lua(Docker 0.7 version). In case some one follows your guide it wont be problem till Kong is running, problem will surface on restart where Docker for Kong will show running but with no service listening on ports 8000,8001, looking at Logs show Kong is not starting because of config missing for Runscope. I had to remove from cassandra plugin table manually Runscope plugin.

**Comment by Tieske** [comment] 2016-04-06 17:12
@harryparmar we're working on loadbalancing and one feature is going to be healthchecks.

Regarding the runscope problem you mentioned, would you mind opening a new issue for that and include some more details for us to investigate?

**Comment by Tieske** [comment] 2016-04-06 17:29
just to make sure; have you seen #1079 ? Please check whether its the same issue before creating a new one

**Comment by harryparmar** [comment] 2016-04-06 17:30
Hi Tieske,

I see in your github, you have already fixed constant.lua file. I pulled docker image for 0.7 which at the time(last month) was missing runscope plugin and followed your quickstart guide to install Runscope plugin which created issue on Kong restart, maybe you have already fixed the docker version too? If not i will explain the problem and fix in detail in new issue,

**Comment by jimmypk** [comment] 2016-04-07 04:22
I have written a plugin for "multiple upstreams for single API endpoint".
My idea is using Consul Server for service discovery. My plugin use Lua Resty DNS to query SRV record from Consul Server. Example:
- My Api is running on docker container (you can run many docker containers for 1 api), all containers register their services to Consul Server (with IP and port) by using Registrator container.
- Point domain api1.abc.com to Kong Server.
- Enable my plugin for this api.
- When user send request to api1.abc.com , my plugin will query SRV record of this service and receive a list of SRV records (they are round robin from Consul).
- After that, proxy user request to the IP and port of this service.

How do you think about this?

**Comment by harryparmar** [comment] 2016-04-11 16:24
Jimmy that sounds very clever, thanks for sharing. when your plugin receives  records from  consul do they contain dead servers as well? if it does, then do you forward request to dead server or request another from Consul? my main concern is in addition to doing basic load balancing but also picking intelligently alive server to forward request to.

**Comment by gomes** [comment] 2016-04-11 21:40
@harryparmar consul do health check https://www.consul.io/intro/getting-started/checks.html

@jimmypk are you planning to open your plugin?

**Comment by gabel** [comment] 2016-09-15 08:45
@jimmypk I like the idea in general the DNS communication may cause a latency overhead that may be shipped around by using consul-template to configure nginx in kong.

**Comment by FryDerm** [comment] 2017-01-11 17:43
Just wondering where you stand on implementing load balancing?  Is this implemented in Kong yet?

**Comment by thibaultcha** [comment] 2017-01-11 19:16
@FryDerm Load balancing has just started being implemented and the 0.10.0rc1 already has some capabilities regarding it (round-robin load balancing based on DNS records or manually specified "upstream targets").

See:
https://github.com/Mashape/kong/releases/tag/0.10.0rc1
https://github.com/Mashape/kong/pull/1735
https://github.com/Mashape/getkong.org/pull/300

**Comment by FryDerm** [comment] 2017-01-11 22:20
@thibaultcha Thank you very much for your response.  I look forward to checking it out.

**Comment by Tieske** [comment] 2017-02-13 15:16
load balancing implemented in 0.10, available in the RC. Remaining is a duplicate of #112 for healthchecks. Closing this.

**Closed by Tieske** 2017-02-13 15:16 UTC

**Comment by IvanovOleg** [comment] 2017-02-21 09:42
Please add a weighted routing policy to allow us to perform a Canary Releases

**Comment by Tieske** [comment] 2017-03-02 10:06
@IvanovOleg 0.10 also has `upstream` and `target` entities, which allow for more fine grained control. Additionally when using SRV dns records, it will use weighted round robin.

But for canary releases, traffic routing is only based on weights/volumes, not on any selection criterias (such as routing specific users or ip addresses)

**Comment by harshavardhanc** [comment] 2019-11-11 06:25
@IvanovOleg Is this feature of having multiple upstreams for a single endpoint is available in 0.9?
