### ISSUE TITLE
how to do?  one request route to multi backend service API  and together the responses.

### ISSUE THREAD

**Issue by shenzhaohui** [Mashape/kong#1833] opened 2016-11-18 16:27 UTC
### Summary

In order to impliment:
http://microservices.io/patterns/apigateway.html

A product details UI can display a lot of information about a product. For example, the Amazon.com details page for POJOs in Action displays:

    Basic information about the book such as title, author, price, etc.
    Your purchase history for the book
    Availability
    Buying options
    Other items that are frequently bought with this book
    Other items bought by customers who bought this book
    Customer reviews
    Sellers ranking
    …

Since the online store uses the Microservices pattern the product details data is spread over multiple services. For example,

    Product Info Service - basic information about the product such as title, author
    Pricing Service - product price
    Order service - purchase history for product
    Inventory service - product availability
    Review service - customer reviews …

Consequently, the code that displays the product details needs to fetch information from all of these services.

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment] 2016-11-18 20:41
duplicate of #155

**Closed by Tieske** 2016-11-18 20:41 UTC
