### ISSUE TITLE
Whitelisting paths/methods

### ISSUE THREAD

**Issue by dlecorfec** [Mashape/kong#1149] opened 2016-04-11 17:37 UTC
I'd like to have granular path control, in order to whitelist some path and method combination.

Example:

Allow GET on /foo
Allow GET and POST on /bar
Deny everything else

It doesn't seem implemented by available plugins. Did I miss something or do I have to write my own plugin?

**Comment by sinzone** [comment] 2016-04-11 20:48
waiting for the #505

**Comment by thefosk** [comment] 2016-04-11 22:12
Closing as duplicate of #505.

**Closed by thefosk** 2016-04-11 22:12 UTC
