### ISSUE TITLE
TimeOut issues

### ISSUE THREAD

**Issue by saithala** [Mashape/kong#2762] opened 2017-08-03 00:25 UTC
We use Kong 0.9.7 as our API gateway running on Docker containers. We use Kong as a proxy for our backend API miroservices. But sporadically we see the following errors in the kong logs

[error] 167#0: *9962591 upstream timed out (110: Connection timed out) while reading response header from upstream. 

There are no entries in the backend (upstream) logs which makes me believe that Kong for some reason did not route the request to the backend. The next subsequent request is processed absolutely fine. Any ideas?

**Comment by p0pr0ck5** [comment] 2017-08-07 02:50
@saithala this possibly sounds like a layer 3/4 networking issue between Kong and the upstream, if you are not seeing any application level errors upstream. Best way to proceed would likely be to capture network traffic of failed requests and see why the connection times out, and dig further upstream to look for signs of potential trouble. The error log indicates a successful TCP connection was made and the full request was sent upstream, but the upstream server never sent back any response.

**Comment by saithala** [comment] 2017-08-07 14:00
@p0pr0ck5 Thanks for the response. From the error log can you please let me know how you concluded that a successful TCP connection was made? Since there were not even entry logs in the upstream, it made be believe that may be the request was not sent to the upstream.
Also I found a similar issue https://github.com/Mashape/kong/issues/2316.  Any further thoughts on this?

**Comment by p0pr0ck5** [comment] 2017-08-07 16:24
The line you posted:

> [error] 167#0: *9962591 upstream timed out (110: Connection timed out) while reading response header from upstream.

The language here is fairly self explanatory: the connection timed out while reading the response header. In http 1.1 proxy pass mechanics, the response is read after fully sending the request to the upstream server. This implies all the following happened previously to the error being recorded:

- The downstream client request was fully received, processed, identified as valid, as passed through the access phase
- An upstream was selected
- A TCP connection was initiated (or reused)
- Kong sent the full contents of the downstream request up to the server, and began waiting for a response

Hopefully this helps you troubleshoot. I am inclined to close this issue if there aren't any more Kong-specific details here, but we can keep this open for a bit while you do some digging on your end. HTH!

**Comment by saithala** [comment] 2017-08-07 17:25
Thanks @p0pr0ck5 . Since this now appears is not a Kong issue, please close it..

**Closed** 2017-08-07 17:25 UTC

**Comment by neterium** [comment] 2018-04-18 11:05
I've exactly the same issue. It happens when the gateway is left unused for a while. Then, the first request returns this error (though it has been router and the upstream server replied) - if I resend the same request, it's starts working as expected. I've read it could be caused by a wrong nginx configuration regarding keep-alive headers, but I did not change anything in that config and it looks fine (at first sight).
